// Run after extracting the original Kenney archives into work/assets/{industrial,nature}.
// Converts OBJ/MTL to local browser data; no runtime dependency or remote requests.
const fs=require('node:fs'),path=require('node:path');
const models={};
for(const [pack,names] of Object.entries({industrial:['building-a','building-b','building-c','building-d','building-e','building-f'],nature:['rock_largeA','rock_largeB','rock_largeC','tree_oak','tree_pineDefaultA']})){
 for(const name of names){
  const base=path.join('work/assets',pack,'Models/OBJ format',name),v=[null],vn=[null],uv=[null],materials={},parts={};let material='default',current;
  for(const line of fs.readFileSync(base+'.mtl','utf8').split(/\r?\n/)){const [op,...args]=line.trim().split(/\s+/);if(op==='newmtl')materials[current=args[0]]={color:[1,1,1]};if(op==='Kd')materials[current].color=args.map(Number);if(op==='map_Kd')materials[current].texture=true;}
  for(const line of fs.readFileSync(base+'.obj','utf8').split(/\r?\n/)){
   const [op,...args]=line.trim().split(/\s+/);
   if(op==='v')v.push(args.slice(0,3).map(Number));if(op==='vn')vn.push(args.map(Number));if(op==='vt')uv.push(args.map(Number));if(op==='usemtl')material=args[0];
   if(op!=='f')continue;
   const part=parts[material]??={...materials[material],positions:[],normals:[],uvs:[]};
   for(let i=1;i<args.length-1;i++)for(const index of [args[0],args[i],args[i+1]]){const [p,t,n]=index.split('/').map(Number);part.positions.push(...v[p]);part.normals.push(...(vn[n]||[0,1,0]));part.uvs.push(...(uv[t]||[0,0]));}
  }
  models[name]=Object.values(parts);
 }
}
fs.writeFileSync('assets/models/kenney.js','// Kenney CC0; see assets/CREDITS.md. Generated by tools/import-models.cjs.\nwindow.KenneyModels='+JSON.stringify(models,(_k,v)=>typeof v==='number'?+v.toFixed(5):v)+';\n');
console.log('Imported',Object.keys(models).length,'models.');
