/* Full-screen battle menus. Values are drafts until Apply is pressed. */
(() => {
 'use strict';
 const $=id=>document.getElementById(id);
 const escape=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 let backAction=null;
 const defaults={volume:.45,quality:'high',difficulty:'normal',sensitivity:1,renderScale:1,shadows:true,postprocessing:true,cameraShake:true};
 function settings(current,apply,back){
  const draft={...defaults,...current};let active='graphics';backAction=()=>{backAction=null;back();};
  const tabs=[['graphics','▣','ГРАФИКА'],['sound','♫','ЗВУК'],['controls','⌘','УПРАВЛЕНИЕ'],['gameplay','⚙','ИГРОВОЙ ПРОЦЕСС']];
  const select=(key,label,options)=>`<label class="setting-row"><span>${label}</span><select data-setting="${key}">${options.map(([value,title])=>`<option value="${value}" ${String(draft[key])===String(value)?'selected':''}>${title}</option>`).join('')}</select></label>`;
  const toggle=(key,label)=>`<label class="setting-row"><span>${label}</span><input type="checkbox" data-setting="${key}" ${draft[key]?'checked':''}></label>`;
  const range=(key,label,min,max,step)=>`<label class="setting-row range-row"><span>${label} <output>${key==='volume'?Math.round(draft[key]*100)+'%':draft[key].toFixed(2)+'×'}</output></span><input data-setting="${key}" type="range" min="${min}" max="${max}" step="${step}" value="${draft[key]}"></label>`;
  function render(){
   const panels={graphics:()=>select('quality','Качество графики',[['high','Высокое'],['low','Производительность']])+select('renderScale','Масштаб рендеринга',[[.5,'50%'],[.75,'75%'],[1,'100%'],[1.25,'125%'],[1.5,'150%']])+toggle('shadows','Динамические тени')+toggle('postprocessing','Постобработка / AO')+'<button id="menuFullscreen" class="menu-button">ПОЛНЫЙ ЭКРАН ↗</button><p class="menu-note">Масштаб меняет чёткость 3D-сцены, не интерфейса. Детализация окружения обновится при следующей загрузке карты. В режиме производительности постобработка отключена.</p>',sound:()=>range('volume','Общая громкость',0,1,.05)+'<p class="menu-note">Регулирует выстрелы, попадания, двигатель и интерфейс. Ноль — отключить звук.</p>',controls:()=>range('sensitivity','Чувствительность мыши и касаний',.25,2.5,.05)+toggle('cameraShake','Тряска камеры при попаданиях')+'<div class="menu-keymap"><span><kbd>W A S D</kbd> Движение</span><span><kbd>Мышь</kbd> Башня и камера</span><span><kbd>ЛКМ / Пробел</kbd> Выстрел</span><span><kbd>Shift</kbd> Оптика</span><span><kbd>Tab</kbd> Состав команд</span><span><kbd>Esc</kbd> Пауза / назад</span></div>',gameplay:()=>select('difficulty','Сложность ботов',[['easy','Лёгкие'],['normal','Обычные'],['hard','Сложные']])+'<p class="menu-note">Применяется со следующего боя с ботами. В сетевом режиме бой не останавливается на паузу.</p><p class="menu-note">Язык интерфейса: русский.</p>'};
   $('modalContent').innerHTML=`<div class="settings-screen"><div class="menu-header"><h2>⚙ НАСТРОЙКИ</h2><small>НАСТРОЙ СВОЮ БИТВУ</small></div><div class="settings-layout"><nav class="settings-nav" aria-label="Разделы настроек">${tabs.map(([key,icon,name])=>`<button class="menu-button ${active===key?'selected':''}" data-settings-tab="${key}" aria-pressed="${active===key}"><b>${icon}</b>${name}</button>`).join('')}</nav><section class="settings-fields"><h3>${tabs.find(t=>t[0]===active)[2]}</h3>${panels[active]()}</section><aside class="settings-preview"><div></div><p>КРАСИВЫЙ МИР.<br>БОЛЬШИЕ СРАЖЕНИЯ.</p></aside></div><div class="menu-footer"><button id="resetSettings" class="menu-button">ПО УМОЛЧАНИЮ</button><span></span><button id="saveSettings" class="menu-button selected">ПРИМЕНИТЬ</button><button id="closeSettings" class="menu-button">НАЗАД</button></div></div>`;
   $('modal').hidden=false;
   document.querySelectorAll('[data-settings-tab]').forEach(b=>b.onclick=()=>{active=b.dataset.settingsTab;render();});
   document.querySelectorAll('[data-setting]').forEach(input=>input.oninput=()=>{const key=input.dataset.setting;draft[key]=input.type==='checkbox'?input.checked:['volume','renderScale','sensitivity'].includes(key)?+input.value:input.value;const output=input.closest('label').querySelector('output');if(output)output.textContent=key==='volume'?Math.round(draft[key]*100)+'%':draft[key].toFixed(2)+'×';});
   $('resetSettings').onclick=()=>{Object.assign(draft,defaults);render();};
   $('saveSettings').onclick=()=>{apply({...draft});backAction();};
   $('closeSettings').onclick=()=>backAction();
   if($('menuFullscreen'))$('menuFullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{ $('menuFullscreen').textContent='ПОЛНЫЙ ЭКРАН НЕДОСТУПЕН'; }};
  }
  render();
 }
 function results({win,reason,own,reward,rows,map,duration,teamSize,onGarage,onAgain}){
  backAction=null;
  const metrics=[[reward.silver,'СЕРЕБРО','◉'],[reward.xp,'ОПЫТ','✦'],[own?.kills||0,'УНИЧТОЖЕНО','♜'],[own?.damage||0,'НАНЕСЕНО УРОНА','◎']];
  const details=[['Место в бою',`${own?.place||'—'} / ${teamSize}`],['Обнаружено противников',own?.spotted||0],['Время на захвате',Math.round(own?.capture||0)+' с'],['Состояние техники',own?.survived?'Сохранена':'Уничтожена']];
  $('modalContent').innerHTML=`<div class="match-report ${win?'won':'lost'}"><div class="report-header"><span>РЕЗУЛЬТАТЫ БОЯ</span><nav aria-label="Разделы результатов"><button data-result-tab="personal" class="active">ЛИЧНЫЙ РЕЗУЛЬТАТ</button><button data-result-tab="team">КОМАНДНЫЙ РЕЗУЛЬТАТ</button><button data-result-tab="details">СТАТИСТИКА</button></nav><small>${escape(map)} · ${Math.floor(duration/60)}:${String(Math.floor(duration%60)).padStart(2,'0')}</small></div><div class="report-heading"><h2>${win?'ПОБЕДА!':'ПОРАЖЕНИЕ'}</h2><p>${escape(reason)}</p></div><section data-result-panel="personal"><div class="report-metrics">${metrics.map(([value,label,icon])=>`<div><i>${icon}</i><strong>${Number(value).toLocaleString('ru-RU')}<small>${label}</small></strong></div>`).join('')}</div><div class="report-panels"><article><h3>БОЕВОЙ РЕЗУЛЬТАТ</h3><b class="report-rank">${own?.place||'—'}<small>МЕСТО ИЗ ${teamSize}</small></b><p>Рейтинг по урону и уничтожениям.<br>Равные результаты — одинаковое место.</p></article><article><h3>НАГРАДА ЗА БОЙ</h3><dl>${Object.entries(reward.parts||{}).filter(([,v])=>v>0).map(([k,v])=>`<div><dt>${escape(({placement:'Место в рейтинге',participation:'Участие',damage:'Урон',kills:'Уничтожения',win:'Победа',spotted:'Разведка',spotting:'Разведка',objective:'Захват',capture:'Захват',survived:'Выживание',base:'Участие',victory:'Победа',survival:'Выживание'})[k]||k)}</dt><dd>+${v} ◉</dd></div>`).join('')}</dl></article><article><h3>ЛИЧНАЯ СТАТИСТИКА</h3><dl>${details.map(([k,v])=>`<div><dt>${k}</dt><dd>${v}</dd></div>`).join('')}</dl></article></div></section><section data-result-panel="team" hidden><div class="results-scroll"><table class="results-table"><caption>Результаты всех участников</caption><thead><tr><th>Место</th><th>Командир / техника</th><th>Урон</th><th>Убито</th><th>Серебро</th><th>Опыт</th></tr></thead><tbody>${rows}</tbody></table></div></section><section data-result-panel="details" hidden><div class="report-details"><h3>ВАШ ВКЛАД В СРАЖЕНИЕ</h3><dl>${[...details,['Нанесённый урон',own?.damage||0],['Уничтожено',own?.kills||0],['Получено серебра',reward.silver],['Получено опыта',reward.xp]].map(([k,v])=>`<div><dt>${k}</dt><dd>${v}</dd></div>`).join('')}</dl></div></section><div class="menu-footer"><button id="returnGarage" class="menu-button">ВЕРНУТЬСЯ В АНГАР</button><button id="playAgain" class="menu-button selected">${onAgain?'СЫГРАТЬ ЕЩЁ РАЗ':'В АНГАР К НОВОМУ БОЮ'}</button><span></span><small>КАЖДЫЙ БОЙ ДЕЛАЕТ ТЕБЯ СИЛЬНЕЕ.</small></div></div>`;
  $('modal').hidden=false;$('returnGarage').onclick=onGarage;$('playAgain').onclick=onAgain||onGarage;
  document.querySelectorAll('[data-result-tab]').forEach(button=>button.onclick=()=>{document.querySelectorAll('[data-result-tab]').forEach(b=>b.classList.toggle('active',b===button));document.querySelectorAll('[data-result-panel]').forEach(panel=>panel.hidden=panel.dataset.resultPanel!==button.dataset.resultTab);});
 }
 document.addEventListener('keydown',event=>{if(event.code==='Escape'&&backAction&&!$('modal').hidden){event.preventDefault();event.stopImmediatePropagation();backAction();}},true);
 window.BattleMenus={settings,results};
})();
