/* Steel Frontier. Original procedural art; Three.js r160, no external assets. */
(() => {
'use strict';
const D=GameData, $=id=>document.getElementById(id), V=THREE.Vector3;
let save=D.clean(Platform.load()), state='garage', paused=false, scene, world, camera, renderer, preview;
let tanks=[],player,bullets=[],particles=[],obstacles=[],solidMeshes=[],ground,arena,rand,trackMarks=[];
let battleTime=0,elapsed=0,capture=0,record,viewYaw=0,viewPitch=0,mouseDown=false,aiming=false,drag=false,dragX=0,lastTime=0,uiTick=0,shake=0,toastTimer,hitTimer;
let matchMode='solo',net=null,netTick=0,countdown=0,countdownClock=null,armorView=false,aimHit=null;
let engineAudio,engineGain,audio,master,navGrid,navN,navStep=8,lastAimPoint=new V();
const keys={}, ray=new THREE.Raycaster(), up=new V(0,1,0), tmp=new V(), roman=['I','II','III','IV','V'];
const markers=new Map(), wheelGeo=new THREE.CylinderGeometry(.48,.48,.32,12), boxGeo=new THREE.BoxGeometry(1,1,1), sphereGeo=new THREE.IcosahedronGeometry(1,1);
const materials=new Map();
const mat=(color,metalness=.08,roughness=.83)=>{const key=color+':'+metalness+':'+roughness;if(!materials.has(key))materials.set(key,new THREE.MeshStandardMaterial({color,metalness,roughness}));return materials.get(key);};
const trackGeo=new THREE.PlaneGeometry(.52,1.5),holeGeo=new THREE.CircleGeometry(1,12),trackMat=new THREE.MeshBasicMaterial({color:0x20231f,transparent:true,opacity:.28,depthWrite:false,polygonOffset:true,polygonOffsetFactor:-2});
function proceduralTexture(kind){const canvas=document.createElement('canvas');canvas.width=canvas.height=256;const c=canvas.getContext('2d'),winter=kind==='winter',desert=kind==='desert';c.fillStyle=winter?'#c7d2d1':desert?'#b9a174':'#718060';c.fillRect(0,0,256,256);let r=D.rng(winter?71:desert?43:29);for(let i=0;i<900;i++){const v=Math.floor(70+r()*80),a=.025+r()*.08;c.fillStyle=winter?`rgba(${v},${v+8},${v+12},${a})`:desert?`rgba(${v+55},${v+40},${v+16},${a})`:`rgba(${v-25},${v},${v-16},${a})`;c.fillRect(r()*256,r()*256,1+r()*5,1+r()*5);}c.strokeStyle=winter?'#aebfc455':desert?'#8f774530':'#4c5d4038';c.lineWidth=2;for(let i=0;i<18;i++){c.beginPath();c.moveTo(0,r()*256);c.bezierCurveTo(70,r()*256,180,r()*256,256,r()*256);c.stroke();}const tex=new THREE.CanvasTexture(canvas);tex.wrapS=tex.wrapT=THREE.RepeatWrapping;tex.repeat.set(arena.size/24,arena.size/24);tex.colorSpace=THREE.SRGBColorSpace;return tex;}
function mesh(g,m,parent,x=0,y=0,z=0){const o=new THREE.Mesh(g,m);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o;}
function box(parent,w,h,d,x,y,z,color){const o=mesh(boxGeo,mat(color),parent,x,y,z);o.scale.set(w,h,d);return o;}
function cyl(parent,r1,r2,h,x,y,z,color,sides=12){return mesh(new THREE.CylinderGeometry(r1,r2,h,sides),mat(color),parent,x,y,z);}
function angle(a){return Math.atan2(Math.sin(a),Math.cos(a));}
function approach(a,b,step){return a+Math.max(-step,Math.min(step,angle(b-a)));}
function chosen(){return D.tanks.find(t=>t.id===save.selected);}
function mergeMeshes(parent,exclude=[],recursive=false){
 parent.updateMatrixWorld(true);const groups=new Map(),list=[];if(recursive)parent.traverse(o=>{if(o.isMesh)list.push(o);});else list.push(...parent.children.filter(o=>o.isMesh));
 const inverse=parent.matrixWorld.clone().invert();for(const o of list){if(exclude.includes(o)||o.material.vertexColors||Array.isArray(o.material))continue;const key=o.material.uuid+':'+o.castShadow;let entry=groups.get(key);if(!entry){entry={material:o.material,cast:o.castShadow,objects:[],positions:[],normals:[]};groups.set(key,entry);}const g=o.geometry.index?o.geometry.toNonIndexed():o.geometry.clone();g.applyMatrix4(new THREE.Matrix4().multiplyMatrices(inverse,o.matrixWorld));entry.positions.push(g.attributes.position.array);entry.normals.push(g.attributes.normal.array);entry.objects.push(o);g.dispose();}
 for(const entry of groups.values()){if(entry.objects.length<2)continue;const length=entry.positions.reduce((n,a)=>n+a.length,0),p=new Float32Array(length),n=new Float32Array(length);let offset=0;for(let i=0;i<entry.positions.length;i++){p.set(entry.positions[i],offset);n.set(entry.normals[i],offset);offset+=entry.positions[i].length;}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(p,3));g.setAttribute('normal',new THREE.BufferAttribute(n,3));const merged=mesh(g,entry.material,parent);merged.castShadow=entry.cast;for(const o of entry.objects)o.parent.remove(o);}
}
function persist(){Platform.save(save);$('saveStatus').textContent=Platform.status;}
function toast(text){$('toast').textContent=text;$('toast').style.opacity=1;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').style.opacity=0,3000);}
function initAudio(){if(audio){audio.resume();return;}try{audio=new (window.AudioContext||window.webkitAudioContext)();master=audio.createGain();master.gain.value=save.settings.volume;master.connect(audio.destination);engineAudio=audio.createOscillator();engineAudio.type='sawtooth';engineGain=audio.createGain();const filter=audio.createBiquadFilter();filter.type='lowpass';filter.frequency.value=170;engineGain.gain.value=0;engineAudio.connect(filter);filter.connect(engineGain);engineGain.connect(master);engineAudio.start();}catch{}}
function sound(type,volume=1){if(!audio||audio.state!=='running')return;const t=audio.currentTime;const gain=audio.createGain();gain.connect(master);const duration=type==='shot'?.35:type==='boom'?.65:.14;gain.gain.setValueAtTime((type==='boom'?.4:type==='shot'?.25:.12)*volume,t);gain.gain.exponentialRampToValueAtTime(.001,t+duration);if(type==='shot'||type==='boom'){const buffer=audio.createBuffer(1,audio.sampleRate*duration,audio.sampleRate);const data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1);const node=audio.createBufferSource();node.buffer=buffer;const filter=audio.createBiquadFilter();filter.type='lowpass';filter.frequency.setValueAtTime(type==='shot'?1800:650,t);filter.frequency.exponentialRampToValueAtTime(80,t+duration);node.connect(filter);filter.connect(gain);node.start();node.stop(t+duration);}else{const o=audio.createOscillator();o.type='sine';o.frequency.setValueAtTime(type==='hit'?420:750,t);o.frequency.exponentialRampToValueAtTime(160,t+duration);o.connect(gain);o.start();o.stop(t+duration);}}

function buildTank(spec,team=0){return Remaster.tank(spec,team);}
function setupScene(kind){
 if(scene){scene.traverse(o=>{if(o.geometry&&o.geometry!==boxGeo&&o.geometry!==wheelGeo&&o.geometry!==sphereGeo&&o.geometry!==holeGeo&&o.geometry!==trackGeo)o.geometry.dispose();});}
 scene=new THREE.Scene();Remaster.lighting(scene);world=new THREE.Group();scene.add(world);obstacles=[];solidMeshes=[];particles=[];bullets=[];trackMarks=[];
 scene.background=new THREE.Color(kind==='garage'?0x8ca39f:D.maps[kind].sky);scene.fog=new THREE.FogExp2(kind==='garage'?0x8ca39f:D.maps[kind].fog,kind==='garage'?.004:.0013);
 const hemi=new THREE.HemisphereLight(kind==='garage'?0xe8f5ef:0xe2eeff,kind==='garage'?0x59645f:0x655c43,kind==='garage'?2.35:1.15);scene.add(hemi);
 const sun=new THREE.DirectionalLight(kind==='garage'?0xfff0c7:0xffecc9,kind==='garage'?4.6:2.6);sun.position.set(-35,65,40);sun.castShadow=true;sun.shadow.mapSize.set(4096,4096);sun.shadow.camera.left=-90;sun.shadow.camera.right=90;sun.shadow.camera.top=90;sun.shadow.camera.bottom=-90;sun.shadow.camera.far=400;sun.shadow.bias=-.0006;sun.shadow.normalBias=.08;scene.add(sun);scene.userData.sun=sun;scene.add(sun.target);if(kind!=='garage')Remaster.sky(scene,kind);const rim=new THREE.DirectionalLight(0xb0d6ff,.65);rim.position.set(40,18,-30);scene.add(rim);
}
function buildHangarSet(){
 const steel=0x4a5b60,dark=0x18252b,warning=0xd0a95e,concrete=0x35444a,orange=0xb8663f;
 // Maintenance gantry above the display platform.
 for(const x of [-14,14]){box(world,.5,9,.5,x,4,1,steel);box(world,1.4,.3,1.4,x,8.6,1,warning);box(world,28,.35,.55,0,8.4,1,steel);box(world,28,.12,.75,0,8.05,1,dark);}
 for(let x=-11;x<=11;x+=5.5){box(world,.08,.08,4,x,8.15,1,warning);const lamp=cyl(world,.12,.12,.1,x,7.96,1,0xc9e2d9,16);lamp.rotation.x=Math.PI/2;}
 // Tool benches and parts racks along the walls.
 for(const side of [-1,1]){
  const x=side*22;box(world,4,.18,13,x,1.05,-9,concrete);box(world,4,2.2,.22,x,2.1,-15,steel);box(world,4,2.2,.22,x,2.1,-3,steel);
  for(const z of [-13,-9,-5]){box(world,3.5,.08,.08,x,2.9,z,warning);for(let j=0;j<4;j++){const tool=cyl(world,.045,.045,.9,x+(j-1.5)*.55,1.7,z,orange,8);tool.rotation.z=Math.PI/2;}}
  for(const z of [-13,-9,-5]){for(let j=0;j<3;j++){const crate=box(world,.8,.55,.8,x+(j-1)*1.05,.55,z,0x5e5545);box(world,.67,.04,.07,x+(j-1)*1.05,.84,z,warning);}}
 }
 // Diagnostic consoles, cables and floor service markings.
 for(const x of [-9,9]){box(world,2.4,1.3,.7,x,.72,10,steel);box(world,1.9,.75,.08,x,1.25,9.62,0x182d32);for(let i=-2;i<=2;i++)cyl(world,.04,.04,.3,x+i*.28,1.42,9.52,0x8fdbe0,8).rotation.x=Math.PI/2;}
 for(let z=-15;z<=15;z+=5){box(world,.12,.015,3.2,-10,.105,z,warning);box(world,.12,.015,3.2,10,.105,z,warning);}
 // Hydraulic lift arms and wheel chocks near the main pad.
 for(const side of [-1,1]){box(world,.32,1.5,.45,side*5.8,.75,3.8,steel);box(world,1.4,.15,.7,side*5.8,1.52,3.8,warning);box(world,.7,.22,.45,side*5.8,.18,4.8,orange);}
 // Ceiling lamps cast a warm industrial pool over the selected tank.
 for(const x of [-10,0,10]){const fixture=box(world,2.2,.12,.65,x,11.2,-2,0x263b40);const lamp=new THREE.PointLight(0xffd49a,18,18);lamp.position.set(x,10.9,-2);scene.add(lamp);fixture.receiveShadow=false;}
 // A second maintenance line adds depth behind the presentation platform.
 for(const z of [-23,-19,-15]){
  box(world,34,.12,.12,0,.12,z,0x91a19d);
  for(const x of [-16,-12,-8,8,12,16]){const mark=box(world,.09,.03,1.25,x,.16,z,warning);mark.rotation.y=(x%8?-.2:.2);}
 }
 // Ventilation ducts with inspection hatches.
 for(const x of [-12,12]){
  const duct=cyl(world,1.15,1.15,28,x,9.9,-19,0x3b4d53,20);duct.rotation.z=Math.PI/2;
  for(let z=-30;z<=-8;z+=4){const hatch=cyl(world,1.25,1.25,.06,x,9.9,z,0x66777a,20);hatch.rotation.z=Math.PI/2;}
 }
 // Welding screens, warning chevrons and hanging service cables.
 for(const x of [-28,28]){
  box(world,.16,4.4,7,x,2.35,-18,0x27383e);
  for(let z=-20;z<=-16;z+=1.2){const stripe=box(world,.04,.42,.9,x+(x>0?-.1:.1),z*.0+2.2,z,warning);stripe.rotation.y=x>0?.55:-.55;}
  for(let i=0;i<4;i++){const cable=cyl(world,.025,.025,4.5,x+(i-1.5)*.45,6.3,-12,0x151e21,8);cable.rotation.z=.12*(i-1.5);}
 }
 // Wheel chocks, oil drums and a pallet of spare road wheels.
 for(const x of [-7,7]){
  for(const z of [-10,-7]){const drum=cyl(world,.5,.5,1.05,x,.55,z,0x5d6870,20);drum.rotation.x=Math.PI/2;box(world,.62,.06,.08,x,.95,z,warning);}
  for(let i=0;i<3;i++){const wheel=cyl(world,.55,.55,.18,x+i*.72-1,.25,-4,0x252b2c,20);wheel.rotation.z=Math.PI/2;const hub=cyl(world,.2,.2,.2,x+i*.72-1,.25,-4,steel,16);hub.rotation.z=Math.PI/2;}
 }
 // Small technical display plaques facing the camera.
 for(const x of [-15,15]){box(world,3.2,1.8,.12,x,3.2,-26.9,0x1b2c32);box(world,2.7,.06,.03,x,3.75,-26.82,warning);for(let j=0;j<4;j++)box(world,.18,.18,.03,x-1+j*.65,3.28,-26.82,j%2?0x80d1c1:0xd05f48);}
}
function hangar(){
 state='garage';paused=false;aiming=false;viewPitch=0;viewYaw=0;countdown=0;countdownClock=null;aimHit=null;Platform.gameplay(false);$('hud').hidden=true;$('garage').hidden=false;$('modal').hidden=true;$('scoreboard').hidden=true;document.exitPointerLock?.();markers.clear();$('markers').innerHTML='';setupScene('garage');
 const floor=box(world,160,.4,160,0,-.4,0,0x727975);floor.receiveShadow=true;
 const pad=cyl(world,7.5,7.6,.2,0,-.03,0,0x858a82,64);const ring=mesh(new THREE.TorusGeometry(7.25,.025,4,80),mat(0xc0ae7e),world,0,.09,0);ring.rotation.x=Math.PI/2;
 const grid=new THREE.GridHelper(100,40,0x516267,0x37474d);grid.position.y=-.18;world.add(grid);
 for(let i=-3;i<=3;i++){box(world,.04,.02,12,i*2,.08,0,0x556368);}
 buildHangarSet();
 for(const x of [-18,18]){for(let z=-30;z<35;z+=10){box(world,.8,14,.8,x,6,z,0x313f45);box(world,1.1,.3,8,x,13,z,0x72827d);box(world,.12,6,.14,x+.5,3,z+.5,0xbcae73);}}
 for(let z=-30;z<35;z+=10)box(world,36,.6,.7,0,13,z,0x36474d);
 box(world,40,15,.6,0,6,-28,0x26383e);
 for(let x=-15;x<=15;x+=6){box(world,4.7,3,.15,x,9,-27.6,0x9ba8a3);box(world,4.7,.08,.18,x,9,-27.4,0x2e4249);}
 const r=D.rng(81);for(let i=0;i<22;i++){let x=(r()-.5)*33,z=-9-r()*16;box(world,1.2+r(),.8+r(),1.2,x,.5,z,0x4d574b);}
 const light=new THREE.PointLight(0x8fdbe0,45,25);light.position.set(6,7,-4);scene.add(light);
 // Bright clerestory glazing and a wide loading door create the open industrial feel.
 const glass=new THREE.MeshStandardMaterial({color:0xcde1dc,roughness:.2,metalness:.05,transparent:true,opacity:.72,side:THREE.DoubleSide});
 for(let x=-16;x<=16;x+=4){const pane=new THREE.Mesh(new THREE.BoxGeometry(3.55,2.2,.08),glass);pane.position.set(x,9.8,-27.55);world.add(pane);box(world,.1,2.45,.16,x-1.87,9.8,-27.48,0x4a5b60);}
 const outside=new THREE.Mesh(new THREE.PlaneGeometry(12,7),new THREE.MeshBasicMaterial({color:0xc9dfc5}));outside.position.set(-11,4,-27.4);world.add(outside);for(const x of [-17,-5])box(world,.35,8,.45,x,4,-27.1,0x4a5b60);box(world,12,.35,.45,-11,8,-27.1,0x4a5b60);
 // Long service pits with removable steel grates.
 for(const x of [-5.2,5.2]){box(world,1.05,.035,13,x,.13,0,0x171f21);for(let z=-6;z<=6;z+=.55)box(world,.98,.045,.08,x,.18,z,0x6e7978);}
 // Thick pneumatic hoses are laid on the floor around the repair point.
 const hoseMat=new THREE.MeshStandardMaterial({color:0x22292a,roughness:.78});
 for(const side of [-1,1]){const curve=new THREE.CatmullRomCurve3([new V(side*2.4,.2,1.2),new V(side*5,.2,2.6),new V(side*7,.2,1.2),new V(side*5.2,.2,-1.6),new V(side*3.2,.2,-1.1)]);const hose=new THREE.Mesh(new THREE.TubeGeometry(curve,38,.075,8,false),hoseMat);hose.castShadow=true;world.add(hose);}
 // Red tool cabinets, workbench and spare wheels.
 for(const x of [-15,-11,11,15]){box(world,2.6,2.4,.42,x,1.35,-25.6,0x8f3e35);box(world,2.1,.06,.05,x,1.92,-25.36,0xd0a95e);for(let j=0;j<3;j++)cyl(world,.055,.055,.22,x-.55+j*.55,1.55,-25.34,0x252a2c,10).rotation.x=Math.PI/2;}
 box(world,6,.22,1.1,0,1.05,-24.5,0x566568);box(world,6,1.2,.18,0,1.6,-24.95,0x39494d);
 for(const x of [-7,7]){const reel=cyl(world,.7,.7,.28,x,.9,-11,0x384348,24);reel.rotation.z=Math.PI/2;for(let i=0;i<3;i++){const spoke=box(world,.08,1.2,.08,x,.9,-11,0xd0a95e);spoke.rotation.z=i*Math.PI/3;}}
 preview=buildTank(D.stats(chosen(),save.levels[save.selected]));world.add(preview.group);preview.group.rotation.y=-.45;
 // Reset the battle lens after an aimed shot. Otherwise the garage inherits the
 // low FOV and close camera distance from the previous match.
 camera.fov=45;camera.zoom=1;camera.near=.15;camera.far=2400;camera.updateProjectionMatrix();
 camera.position.set(10.8,6.8,13.2);camera.lookAt(0,1.2,0);renderGarage();Remaster.armorMask(preview,armorView,D.stats(chosen(),save.levels[save.selected]));
 if(engineGain)engineGain.gain.value=0;
}
const tankSVG='<svg viewBox="0 0 130 60" aria-hidden="true"><path d="M18 36 L26 27 H66 L70 20 H89 L93 30 H108 L119 39 L115 50 H19 L11 44Z M88 25 L126 23 L127 27 L90 29Z"/><path d="M23 45H110" stroke="#15232a" stroke-width="9"/><g fill="#a8b4aa"><circle cx="27" cy="45" r="4"/><circle cx="42" cy="45" r="4"/><circle cx="57" cy="45" r="4"/><circle cx="72" cy="45" r="4"/><circle cx="87" cy="45" r="4"/><circle cx="102" cy="45" r="4"/></g></svg>';
function renderGarage(){
 const owned=!!save.owned[save.selected];
 const armorSpec=D.stats(chosen(),save.levels[save.selected]),zoneNames=['Лоб корпуса','Нижний лоб','Борта','Корма','Лоб башни','Борта башни','Корма башни','Крыша','Гусеницы'];
 $('armorLegend').hidden=!armorView;
 $('armorLegend').innerHTML=D.armorZones.map((z,i)=>{const mm=D.armorThickness(armorSpec,z);return '<span style="color:'+D.armorColor(mm)+'">■ '+zoneNames[i]+': '+mm+' мм</span>';}).join('')+'<small>Цвет — толщина брони: зелёный — тонкая, красный — толстая. Угол и орудие влияют на пробитие.</small>';
 if(armorView)Remaster.armorMask(preview,true,armorSpec);
 const t=chosen(),s=D.stats(t,save.levels[t.id]),next=D.stats(t,Math.min(5,s.level+1));$('silver').textContent=save.silver.toLocaleString('ru');$('xp').textContent=save.xp.toLocaleString('ru');$('career').textContent=`${save.battles} боёв · ${save.wins} побед`;$('saveStatus').textContent=Platform.status;
 $('nations').innerHTML=D.nations.map((n,i)=>`<button class="${i===t.n?'active':''}" data-nation="${i}">${n}</button>`).join('');$('nations').querySelectorAll('button').forEach(b=>b.onclick=()=>selectTank(`${b.dataset.nation}-${t.c}`));
 $('tankClass').textContent=`${t.cls.toUpperCase()} / ${roman[s.level-1]}`;$('tankName').textContent=t.name;$('tankDesc').textContent=t.description;$('nationLabel').textContent=t.nation.toUpperCase();
 const entries=[['Огневая мощь',s.damage+' ед.',s.damage/300],['Прочность',s.hp+' HP',s.hp/1600],['Скорость',Math.round(s.speed*3.6)+' км/ч',s.speed/20],['Масса',s.mass+' т',s.mass/70],['Двигатель',s.power+' л.с.',s.power/800],['Броня',s.armor+'%',s.armor/40],['Перезарядка',s.reload.toFixed(2)+' с',1-s.reload/7]];
 $('stats').innerHTML=entries.map(([name,value,ratio])=>`<div class="stat"><div><span>${name}</span><b>${value}</b></div><div class="stat-track"><i style="width:${Math.min(100,ratio*100)}%"></i></div></div>`).join('');
 $('level').textContent=roman[s.level-1];$('levelBars').innerHTML=roman.map((_,i)=>`<i class="${i<s.level?'on':''}"></i>`).join('');
 $('upgradeInfo').textContent=s.level===5?'Машина полностью модернизирована. К бою готова.':`Следующий уровень: +${next.hp-s.hp} HP · +${next.damage-s.damage} урона · +2% брони`;
 $('upgradeBtn').textContent=s.level===5?'Максимальный уровень':`Прокачать · ${D.costs[s.level].toLocaleString('ru')} ◉`;$('upgradeBtn').disabled=s.level===5||save.silver<D.costs[s.level];
 $('tankCards').innerHTML=D.tanks.filter(v=>v.n===t.n).map(v=>`<button class="tank-card ${v.id===t.id?'selected':''}" data-tank="${v.id}" aria-label="Выбрать танк ${v.name}"><small>${v.cls.toUpperCase()}</small><span class="card-num">0${v.c+1}</span><strong>${v.name}</strong><em>${save.owned[v.id]?roman[save.levels[v.id]-1]+' УРОВЕНЬ':'🔒 '+D.price(v.id).xp+' XP / '+D.price(v.id).silver+' ◉'} ${v.id===t.id?'· ВЫБРАН':''}</em>${tankSVG}</button>`).join('');$('tankCards').querySelectorAll('button').forEach(b=>b.onclick=()=>selectTank(b.dataset.tank));$('mapSelect').value=save.map;updateMapCard();
 $('battleBtn').disabled=!owned;$('unlockPanel').hidden=owned;const price=D.price(save.selected);$('unlockInfo').textContent=`Исследование ${price.xp} опыта · покупка ${price.silver} серебра`;$('unlockBtn').disabled=save.xp<price.xp||save.silver<price.silver;$('upgradeBtn').disabled=$('upgradeBtn').disabled||!owned;$('armorBtn').textContent=armorView?'МАСКА БРОНИ: ВКЛ':'МАСКА БРОНИ: ВЫКЛ';
}
function selectTank(id){save.selected=id;save.nation=chosen().n;persist();world.remove(preview.group);preview=buildTank(D.stats(chosen(),save.levels[id]));preview.group.rotation.y=-.45;world.add(preview.group);Remaster.armorMask(preview,armorView,D.stats(chosen(),save.levels[save.selected]));sound('ui');renderGarage();}
function updateMapCard(){const m=D.maps[save.map];$('mapPreview').innerHTML=`<span>0${Object.keys(D.maps).indexOf(save.map)+1}</span><div>${m.name.toUpperCase()}<small>${m.subtitle}</small></div>`;$('mapPreview').style.backgroundColor=save.map==='desert'?'#796341':save.map==='winter'?'#506a77':'#334333';updateModeCard();}
function updateModeCard(){const lan=$('modeSelect').value==='lan';$('modeName').textContent=lan?'◈ ЛОКАЛЬНАЯ СЕТЬ':'◈ КОМАНДНЫЙ БОЙ';$('modeSize').textContent=lan?'1 × 1':'3 × 3';$('modeDescription').textContent=lan?'Создайте лобби или войдите по коду через Radmin VPN.':'Уничтожьте противника или удержите центральную базу.';$('modeNote').textContent=lan?'НУЖЕН ЗАПУСК ЧЕРЕЗ PLAY.CMD НА КОМПЬЮТЕРЕ-ХОСТЕ':'ОДИНОЧНАЯ ИГРА • СОЮЗНИКИ И ВРАГИ — БОТЫ';$('battleBtn').innerHTML=lan?'ЛОББИ <span>→</span>':'В БОЙ <span>→</span>';}

// Общая высота ландшафта. Центр оставляем проходимым для базы, а за его пределами
// смешиваем крупные холмы, поперечные гряды и мелкую неровность поверхности.
function height(x,z){
 if(!arena)return 0;
 const edge=Math.min(1,Math.max(0,(Math.max(Math.abs(x),Math.abs(z))-22)/42));
 const center=Math.max(.35,edge);
 const broad=Math.sin(x*.018+Math.sin(z*.011)*.8)*Math.cos(z*.015-x*.006);
 const ridges=Math.sin((x+z)*.032+Math.sin(x*.009)*1.5)+.55*Math.cos((x-z)*.047);
 const detail=Math.sin(x*.11+z*.07)*Math.cos(z*.095-x*.04);
 let h;
 if(arena===D.maps.desert){
  const dunes=Math.sin(x*.031+z*.012)+.55*Math.sin(z*.052-x*.018);
  h=(broad*5.2+ridges*3.4+dunes*2.4+detail*.7)*center;
 }else if(arena===D.maps.winter){
  const snowRidges=Math.sin(z*.026+x*.014)*Math.cos(x*.021)+.5*Math.sin((x-z)*.041);
  h=(broad*4.8+snowRidges*3.8+detail*.55)*center;
 }else{
  h=(broad*5.5+ridges*3.8+detail*.8)*center;
 }
 // Лёгкие впадины вокруг центрального поля дают естественный силуэт, но не мешают старту.
 const basin=Math.max(0,1-Math.hypot(x,z)/85);
 return h*(1-basin*.38);
}
function obstacle(obj,x,z,r){obstacles.push({x,z,r,object:obj});obj.updateMatrixWorld(true);obj.traverse(o=>{if(o.isMesh)solidMeshes.push(o);});}
function building(x,z,w,d,h,industrial=false){const g=new THREE.Group();g.position.set(x,height(x,z),z);world.add(g);box(g,w,h,d,0,h/2,0,industrial?0x6a7779:arena===D.maps.desert?0xc2ae86:0xa0a391);box(g,w+.3,.25,d+.3,0,h,0,0x515c5d);
 if(!industrial){const rw=w/2+.4,rd=d/2+.4;const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute([-rw,0,-rd,rw,0,-rd,0,2.1,-rd,-rw,0,rd,rw,0,rd,0,2.1,rd],3));geo.setIndex([0,2,1,3,4,5,0,3,5,0,5,2,1,2,5,1,5,4,0,1,4,0,4,3]);geo.computeVertexNormals();mesh(geo,mat(arena===D.maps.winter?0xc6d2d2:0x626957),g,0,h,0);}
 for(const side of [-1,1])for(let a=-w/2+1.2;a<w/2-.5;a+=2){box(g,.65,1.1,.09,a,h*.58,side*(d/2+.06),0x34474a);box(g,.8,.13,.17,a,h*.58-.6,side*(d/2+.1),0x7d8984);}
 box(g,1.2,2.3,.13,w*.18,1.15,d/2+.05,0x50584d);Remaster.building(g,w,d,h,industrial,arena===D.maps.desert?'desert':arena===D.maps.winter?'winter':'training');obstacle(g,x,z,Math.hypot(w,d)*.5+.15);
}
function rock(x,z,r){const o=mesh(new THREE.IcosahedronGeometry(r,2),mat(arena===D.maps.desert?0x9d886d:arena===D.maps.winter?0x8a9b9e:0x777e72),world,x,height(x,z)+r*.46,z);o.scale.set(1.2,.8,1);o.rotation.set(rand()*.4,rand()*6,.2);obstacle(o,x,z,r*1.08);}
function tree(x,z){const g=new THREE.Group();g.position.set(x,height(x,z),z);world.add(g);const h=4+rand()*4;cyl(g,.15,.25,h,0,h/2,0,0x535147,6);for(let j=0;j<3;j++)cyl(g,0,2-j*.4,3.6,0,h-1+j*1.2,0,arena===D.maps.winter?0x768e86:0x4a6350,7);}
function buildBackdrop(){const size=arena.size,isWinter=arena===D.maps.winter,isDesert=arena===D.maps.desert,far=size*.7;
 if(!isDesert){for(let side of [-1,1])for(let i=-8;i<=8;i++){const x=i*18+(rand()-.5)*7,z=side*(far+rand()*22);if(isWinter){const h=10+rand()*24;box(world,10+rand()*9,h,9,x,h/2-1,z,0x60727a);if(i%3===0)cyl(world,1.1,1.5,h+15,x+4,(h+15)/2,z,0x718087,10);}else{const g=new THREE.Group();g.position.set(x,-2,z);world.add(g);const h=9+rand()*12;cyl(g,.28,.45,h,0,h/2,0,0x3f463c,6);for(let j=0;j<3;j++)cyl(g,0,3.4-j*.7,5.5,0,h-2+j*1.8,0,0x405c49,7);}}
 }else{for(let side of [-1,1])for(let i=-7;i<=7;i++){const x=i*24+(rand()-.5)*10,z=side*(far+rand()*20),h=5+rand()*14;box(world,9+rand()*13,h,8,x,h/2-2,z,0x8e795b);if(i%4===0)cyl(world,1.2,1.8,h+11,x+5,(h+11)/2-2,z,0x9c8968,10);}}
 if(arena===D.maps.training){for(let i=-5;i<=5;i++){const x=i*22,z=far*.94+(i%2)*8,w=8+rand()*5,h=5+rand()*5;box(world,w,h,7,x,h/2-1,z,0x777867);box(world,w+.4,.5,7.4,x,h,z,0x4e5549);}}
}
function scatterProps(){const isWinter=arena===D.maps.winter,isDesert=arena===D.maps.desert;for(let i=0;i<26;i++){const x=(rand()-.5)*(arena.size-30),z=(rand()-.5)*(arena.size-30);if(Math.abs(x)<15||obstacles.some(o=>Math.hypot(o.x-x,o.z-z)<o.r+3))continue;const g=new THREE.Group();g.position.set(x,height(x,z),z);world.add(g);if(i%3===0){for(let k=0;k<3;k++){const b=cyl(g,.32,.32,.8,(k-1)*.7,.4,0,isDesert?0x756241:0x5c6868,12);b.rotation.z=k===2?Math.PI/2:0;}}else if(i%3===1){box(g,2.2,.85,1.2,0,.43,0,isWinter?0x6b7675:0x746d50);box(g,1.9,.12,1.25,0,.9,0,0x424b44);}else{for(let k=-2;k<=2;k++)box(g,.12,1.4,.12,k*.65,.7,0,0x545a50);box(g,3.1,.12,.12,0,.9,0,0x545a50);}}
}
function buildMap(){
 rand=D.rng(arena.seed);const size=arena.size;const geo=new THREE.PlaneGeometry(size,size,220,220);geo.rotateX(-Math.PI/2);const pos=geo.attributes.position, colors=[];for(let i=0;i<pos.count;i++){const x=pos.getX(i),z=pos.getZ(i);pos.setY(i,height(x,z));const c=new THREE.Color(arena.ground);let tint=.9+rand()*.16;if(Math.abs(x)<5||Math.abs(z)<4)tint*=.87;c.multiplyScalar(tint);colors.push(c.r,c.g,c.b);}geo.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));geo.computeVertexNormals();ground=mesh(geo,Remaster.terrainMaterial(arena===D.maps.winter?'winter':arena===D.maps.desert?'desert':'training',size),world);ground.receiveShadow=true;ground.castShadow=false;
 const isWinter=arena===D.maps.winter;
 const positions=isWinter?[[-28,-45,13,16,9],[26,-32,12,19,10],[-31,28,17,12,9],[29,45,16,13,10],[-63,0,12,18,8],[65,-4,14,18,9]]:[[-28,-30,9,11,6],[27,30,10,12,6],[-40,24,9,9,5],[38,-25,11,8,6]];
 for(const p of positions)building(...p,isWinter);
 for(const side of [-1,1])for(const flank of [-1,1])for(let i=0;i<4;i++){const x=flank*(62+i*34),z=side*(64+(i%2)*48);building(x,z,9+rand()*8,10+rand()*10,isWinter?12+rand()*6:5+rand()*4,isWinter);}
 const apron=mesh(new THREE.PlaneGeometry(2200,2200),Remaster.terrainMaterial(arena===D.maps.winter?'winter':arena===D.maps.desert?'desert':'training',2200),world,0,-5,0);apron.rotation.x=-Math.PI/2;apron.castShadow=false;
 for(let i=0;i<(isWinter?22:38);i++){const x=(rand()-.5)*(size-24),z=(rand()-.5)*(size-34);if(Math.abs(x)<15||Math.abs(z)>size*.37||obstacles.some(o=>Math.hypot(o.x-x,o.z-z)<o.r+8))continue;rock(x,z,2+rand()*3.5);}
 for(const [x,z] of [[-17,-13],[18,15],[-55,-50],[54,48]]){const g=new THREE.Group();g.position.set(x,height(x,z),z);world.add(g);box(g,9,1.5,1.4,0,.75,0,isWinter?0x8c9a9b:0x84866f);obstacle(g,x,z,4.8);}
 for(let i=0;i<14;i++){const x=(rand()>.5?1:-1)*(25+rand()*45),z=(rand()-.5)*140;if(obstacles.some(o=>Math.hypot(o.x-x,o.z-z)<o.r+4))continue;const g=new THREE.Group();g.position.set(x,height(x,z),z);world.add(g);box(g,2,1.6,2,0,.8,0,0x716c50);box(g,2.05,.13,2.05,0,1.3,0,0x434b43);obstacle(g,x,z,1.45);}
 if(isWinter){for(const x of [-55,56]){cyl(world,2,2.8,25,x,12.5,-65,0x677b82);for(let j=0;j<3;j++)cyl(world,2.06,2.06,1.1,x,15+j*4,-65,0x9b9183);}}
 scatterProps();buildBackdrop();
 for(const s of [-1,1]){box(world,size,3,1,0,0,s*size/2,0x707e76);box(world,1,3,size,s*size/2,0,0,0x707e76);}
 const ring=mesh(new THREE.RingGeometry(11.7,12,72),new THREE.MeshBasicMaterial({color:0xddcc92,side:THREE.DoubleSide,transparent:true,opacity:.75}),world,0,.2,0);ring.rotation.x=-Math.PI/2;const pole=cyl(world,.08,.08,6,0,3,0,0xb4b7a3,8);const flag=box(world,1.8,1,.05,.95,5.3,0,0xc3b784);pole.castShadow=false;flag.castShadow=false;
 Remaster.environment(world,arena,height,rand);world.updateMatrixWorld(true);makeNavigation();
}
function blocked(x,z,r=2.1){return Math.abs(x)>arena.size/2-r-1||Math.abs(z)>arena.size/2-r-1||obstacles.some(o=>(x-o.x)**2+(z-o.z)**2<(r+o.r)**2);}
function makeNavigation(){navN=Math.floor(arena.size/navStep);navGrid=new Uint8Array(navN*navN);for(let z=0;z<navN;z++)for(let x=0;x<navN;x++)navGrid[z*navN+x]=blocked((x+.5)*navStep-arena.size/2,(z+.5)*navStep-arena.size/2,2.5)?1:0;}
function route(ax,az,bx,bz){const idx=(x,z)=>Math.max(0,Math.min(navN-1,Math.floor((z+arena.size/2)/navStep)))*navN+Math.max(0,Math.min(navN-1,Math.floor((x+arena.size/2)/navStep)));const start=idx(ax,az);let goal=idx(bx,bz);if(navGrid[goal]){let best=Infinity;for(let i=0;i<navGrid.length;i++)if(!navGrid[i]){const d=(i%navN-goal%navN)**2+(Math.floor(i/navN)-Math.floor(goal/navN))**2;if(d<best){best=d;goal=i;}}}const open=[start],cost=new Float32Array(navN*navN).fill(Infinity),prev=new Int32Array(navN*navN).fill(-1),closed=new Uint8Array(navN*navN);cost[start]=0;let loops=0;const heuristic=i=>Math.hypot(i%navN-goal%navN,Math.floor(i/navN)-Math.floor(goal/navN));while(open.length&&loops++<12000){let k=0;for(let i=1;i<open.length;i++)if(cost[open[i]]+heuristic(open[i])<cost[open[k]]+heuristic(open[k]))k=i;const current=open.splice(k,1)[0];if(current===goal){const p=[];let v=goal;while(v!==start&&v!==-1){p.push({x:(v%navN+.5)*navStep-arena.size/2,z:(Math.floor(v/navN)+.5)*navStep-arena.size/2});v=prev[v];}return p.reverse();}closed[current]=1;const x=current%navN,z=Math.floor(current/navN);for(const [dx,dz] of [[1,0],[-1,0],[0,1],[0,-1],[1,1],[-1,1],[1,-1],[-1,-1]]){const nx=x+dx,nz=z+dz;if(nx<0||nz<0||nx>=navN||nz>=navN)continue;const n=nz*navN+nx;if(navGrid[n]||closed[n]||(dx&&dz&&(navGrid[z*navN+nx]||navGrid[nz*navN+x])))continue;const nc=cost[current]+(dx&&dz?1.414:1);if(nc<cost[n]){cost[n]=nc;prev[n]=current;if(!open.includes(n))open.push(n);}}}return [];}
function spawn(spec,team,index,isPlayer=false){const model=buildTank(spec,team);const x=(index-1)*19,z=(team===0?-1:1)*(arena.size*.4);model.group.position.set(x,height(x,z),z);world.add(model.group);const t={...model,spec,team,isPlayer,hp:spec.hp,yaw:team===0?0:Math.PI,turretYaw:team===0?0:Math.PI,reload:1+index*.25,speed:0,alive:true,target:null,think:rand()*.4,path:[],navTime:0,seen:false,aimTime:0,stuck:0,trackTime:0,name:isPlayer?'Вы':(team===0?['Кедр','Сокол','Риф'][index]:['Коршун','Кремень','Буран'][index])};model.group.rotation.y=t.yaw;Remaster.suspension(t,height,1/60);model.hitMeshes.forEach(o=>o.userData.tank=t);tanks.push(t);if(!isPlayer){const el=document.createElement('div');el.className='marker '+(team===0?'friendly':'');$('markers').append(el);markers.set(t,el);}return t;}
function specFromNet(data){const base=D.tanks.find(t=>t.id===data?.id)||chosen();return D.stats(base,Math.max(1,Math.min(5,Number(data?.level)||1)));}
function startBattle(options={}){
 if(!options.lan&&!save.owned[save.selected]){toast('Сначала исследуйте и купите танк');return;}countdown=5;countdownClock=null;Object.keys(keys).forEach(k=>keys[k]=false);$('countdown').hidden=false;$('countNumber').textContent='5';
 if(options instanceof Event)options={};initAudio();$('modal').hidden=true;$('garage').hidden=true;$('hud').hidden=false;state='battle';paused=false;matchMode=options.lan?'lan':'solo';arena=D.maps[options.map||save.map]||D.maps.training;setupScene(options.map||save.map);buildMap();tanks=[];markers.clear();$('markers').innerHTML='';elapsed=0;battleTime=arena.time;capture=0;viewYaw=matchMode==='lan'&&net?.role==='guest'?Math.PI:0;viewPitch=0;mouseDown=false;aiming=false;record={damage:0,kills:0,spotted:0,capture:0,life:0,win:false,survived:false};
 if(matchMode==='lan'){
  const hostSpec=specFromNet(options.host),guestSpec=specFromNet(options.guest),host=spawn(hostSpec,0,1,net.role==='host'),guest=spawn(guestSpec,1,1,net.role==='guest');player=net.role==='host'?host:guest;const remote=net.role==='host'?guest:host;remote.remote=true;remote.name=net.role==='host'?(net.guestName||'Соперник'):(net.hostName||'Хост');net.remote=remote;net.input={};netTick=0;
 }else{
  for(let i=0;i<3;i++){const s=i===1?D.stats(chosen(),save.levels[save.selected]):D.stats(D.tanks[chosen().n*3+i],save.levels[save.selected]);const t=spawn(s,0,i,i===1);if(i===1)player=t;}
  for(let i=0;i<3;i++)spawn(D.stats(D.tanks[3+i],Math.max(1,save.levels[save.selected]-(save.settings.difficulty==='easy'?1:0))),1,i);
 }
 $('playerName').textContent=player.spec.name.toUpperCase();$('mapName').textContent=arena.name.toUpperCase();$('killfeed').innerHTML='';$('hitMessage').textContent='';$('tutorialHint').textContent=matchMode==='lan'?'ЛОКАЛЬНАЯ СЕТЬ 1 × 1 · уничтожьте танк соперника':save.tutorial?'':'W / S — движение, A / D — поворот корпуса. Shift — оптика, ЛКМ — выстрел. База A находится в центре карты.';camera.position.copy(player.group.position).add(new V(0,7,-13));Platform.gameplay(true);updateHUD();
}
async function lanApi(path,data){const response=await fetch('/api/lan/'+path,{method:data?'POST':'GET',headers:data?{'Content-Type':'application/json'}:{},body:data?JSON.stringify(data):undefined,cache:'no-store'});const result=await response.json().catch(()=>({error:'Сервер не ответил'}));if(!response.ok)throw new Error(result.error||'Ошибка локальной сети');return result;}
function localSpec(){return {id:save.selected,level:save.levels[save.selected]};}
function closeLan(){if(net)netSend('leave',{});net=null;$('modal').hidden=true;}
function netSend(type,data){if(!net)return Promise.resolve();return lanApi('send',{code:net.code,token:net.token,type,data}).catch(()=>{});}
function lobbyView(){if(!net)return;const host=net.role==='host',ready=!!net.guest,players=net.players||[];$('modalContent').innerHTML=`<div class="eyebrow">ЛОКАЛЬНАЯ СЕТЬ · ${host?'ХОСТ':'ГОСТЬ'}</div><h2>Лобби 1 × 1</h2><div class="lan-code">${net.code}</div><p class="lan-status">${players.length<2?'Ожидание второго игрока…':'Соперник подключён: '+(players.find(p=>p.role!==net.role)?.name||'Командир')}</p>${host?`<p>Передайте другу код и адрес Radmin-сети:</p><p class="lan-address">${(net.addresses||[location.origin]).join('<br>')}</p><button id="copyInvite" class="secondary">КОПИРОВАТЬ ПРИГЛАШЕНИЕ</button><button id="lanStart" class="primary" ${ready?'':'disabled'}>НАЧАТЬ БОЙ →</button>`:'<p>Танк выбран. Ждём, когда хост начнёт бой.</p>'}<button id="lanClose" class="text-btn">← Покинуть лобби</button>`;$('lanClose').onclick=closeLan;if(host){$('copyInvite').onclick=async()=>{const text=`Стальной рубеж — лобби ${net.code}\n${(net.addresses||[location.origin])[0]}`;await navigator.clipboard?.writeText(text);toast('Приглашение скопировано');};$('lanStart').onclick=()=>{if(!net.guest)return;const payload={map:save.map,host:localSpec(),guest:net.guest};netSend('start',payload);startBattle({...payload,lan:true});};}}
async function lanPoll(){if(!net)return;try{const result=await lanApi(`poll?code=${encodeURIComponent(net.code)}&token=${encodeURIComponent(net.token)}&since=${net.since||0}`);net.since=result.seq;net.players=result.room.players;for(const message of result.messages)handleNetMessage(message);if(state==='garage'&&!$('modal').hidden)lobbyView();net.failures=0;}catch(error){if(net&&++net.failures>5){toast(error.message);if(state==='battle')endBattle(false,'Соединение с локальным сервером потеряно.');net=null;return;}}if(net)setTimeout(lanPoll,state==='battle'?70:350);}
function handleNetMessage(message){if(!net)return;if(message.type==='joined'){net.players=message.data.players;lobbyView();}else if(message.type==='ready'&&net.role==='host'){net.guest=message.data.spec;net.guestName=message.data.name;lobbyView();}else if(message.type==='start'&&net.role==='guest'){startBattle({...message.data,lan:true});}else if(message.type==='input'&&net.role==='host'){net.input=message.data||{};}else if(message.type==='snapshot'&&net.role==='guest'){applyNetSnapshot(message.data);}else if(message.type==='end'&&state==='battle'){endBattle(message.data.winner===player.team,message.data.reason||'Сетевой бой завершён.');}else if(message.type==='leave'){toast('Соперник покинул лобби');}}
async function createLan(){try{const info=await lanApi('info'),data=await lanApi('create',{name:'Командир'});net={...data,addresses:info.addresses?.length?info.addresses:[location.origin],since:0,players:data.players,failures:0};lobbyView();lanPoll();}catch(error){showModal(`<div class="eyebrow">ЛОКАЛЬНАЯ СЕТЬ</div><h2>Сервер не запущен</h2><p>${error.message}. Запустите игру через <b>PLAY.cmd</b>, а не прямым открытием index.html.</p><button id="lanBack" class="secondary">← Назад</button>`);$('lanBack').onclick=showLan;}}
async function joinLan(){const input=$('lanCode'),joinButton=$('lanJoin'),code=input.value.toUpperCase().replace(/[^A-Z2-9]/g,'');if(code.length!==5){input.focus();return;}joinButton.disabled=true;try{const data=await lanApi('join',{code,name:'Соперник'});net={...data,since:0,players:data.players,failures:0};netSend('ready',{spec:localSpec(),name:'Соперник'});lobbyView();lanPoll();}catch(error){$('lanError').textContent=error.message;joinButton.disabled=false;}}
function showLan(){showModal('<div class="eyebrow">ЛОКАЛЬНАЯ СЕТЬ · RADMIN VPN</div><h2>Бой 1 × 1</h2><p>Хост создаёт лобби и отправляет другу адрес сервера вместе с кодом. Оба игрока должны открыть игру через один и тот же компьютер-хост.</p><div class="lan-actions"><button id="lanCreate" class="primary">СОЗДАТЬ ЛОББИ</button><div><input id="lanCode" maxlength="5" placeholder="КОД" style="width:100%;padding:16px;background:#0d1a20;border:1px solid #ffffff25;color:#fff;text-transform:uppercase"><button id="lanJoin" class="secondary">ВОЙТИ ПО КОДУ</button></div></div><p id="lanError" class="enemy"></p><button id="lanCancel" class="text-btn">← Назад в ангар</button>');$('lanCreate').onclick=createLan;$('lanJoin').onclick=joinLan;$('lanCancel').onclick=()=>{$('modal').hidden=true;};$('lanCode').onkeydown=e=>{if(e.key==='Enter')joinLan();};}
function updateRemote(t,dt){const i=net?.input||{},accel=(i.w?1:0)-(i.s?1:0),turn=(i.a?1:0)-(i.d?1:0);t.yaw+=turn*t.spec.turn*dt*(t.trackTime?.45:1);accelerateTank(t,accel,dt,turn);moveTank(t,dt);t.group.rotation.y=t.yaw;t.turretYaw=approach(t.turretYaw,Number.isFinite(i.yaw)?i.yaw:t.turretYaw,t.spec.turret*dt);t.turret.rotation.y=angle(t.turretYaw-t.yaw);t.remoteAim=!!i.aiming;if(Array.isArray(i.target)&&i.target.length===3){const target=new V(i.target[0],i.target[1],i.target[2]),delta=target.clone().sub(muzzlePos(t));t.gunPivot.rotation.x=THREE.MathUtils.clamp(-Math.atan2(delta.y,Math.hypot(delta.x,delta.z)),-.32,.22);if(i.fire)fire(t,target);}}
function netSnapshot(){return {time:battleTime,capture,countdown,tanks:tanks.map(t=>({team:t.team,x:t.group.position.x,y:t.group.position.y,z:t.group.position.z,yaw:t.yaw,turret:t.turretYaw,hp:t.hp,alive:t.alive,reload:t.reload,speed:t.speed,vy:t.suspension?.vy||0,grounded:t.suspension?.grounded!==false,pitch:t.group.rotation.x,roll:t.group.rotation.z}))};}
function applyNetSnapshot(data){if(!data?.tanks||state!=='battle')return;battleTime=data.time;capture=data.capture;for(const s of data.tanks){const t=tanks.find(v=>v.team===s.team);if(!t)continue;const previous=t.group.position.clone(),alpha=t.isPlayer?.22:.62;t.group.position.lerp(new V(s.x,s.y,s.z),alpha);t.yaw=angle(t.yaw+angle(s.yaw-t.yaw)*alpha);t.turretYaw=angle(t.turretYaw+angle(s.turret-t.turretYaw)*alpha);t.group.rotation.y=t.yaw;t.turret.rotation.y=angle(t.turretYaw-t.yaw);if(t.alive&&!s.alive)makeWreck(t);t.hp=s.hp;t.alive=s.alive;t.reload=s.reload;if(t.suspension){t.suspension.y=t.group.position.y;t.suspension.vy=s.vy||0;t.suspension.grounded=s.grounded!==false;}
 if(!t.isPlayer){t.speed=s.speed;Remaster.suspension(t,height,.1,Math.sign(t.speed)*previous.distanceTo(t.group.position));t.group.position.y=s.y;t.suspension.y=s.y;t.suspension.vy=s.vy||0;t.suspension.grounded=s.grounded!==false;t.group.rotation.x=s.pitch||0;t.group.rotation.z=s.roll||0;}}}
function networkStep(dt){if(matchMode!=='lan'||!net)return;netTick-=dt;if(net.role==='host'){for(const t of tanks)if(t.remote&&t.alive)updateRemote(t,dt);if(netTick<=0){netTick=.1;netSend('snapshot',netSnapshot());}}else if(netTick<=0){netTick=.055;netSend('input',{w:!!(keys.KeyW||keys.ArrowUp),s:!!(keys.KeyS||keys.ArrowDown),a:!!(keys.KeyA||keys.ArrowLeft),d:!!(keys.KeyD||keys.ArrowRight),yaw:viewYaw,aiming,fire:!!(mouseDown||keys.Space),target:[lastAimPoint.x,lastAimPoint.y,lastAimPoint.z]});}}
function los(a,b){const origin=a.group.position.clone().add(new V(0,2,0)),end=b.group.position.clone().add(new V(0,1.5,0));const direction=end.sub(origin),len=direction.length();ray.set(origin,direction.normalize());ray.far=len;return ray.intersectObjects(solidMeshes,false).length===0;}
function updateBot(t,dt){
 const p=t.group.position;t.think-=dt;t.navTime-=dt;const difficulty=save.settings.difficulty;const cfg=difficulty==='easy'?{reaction:.9,spread:.055,aggression:.7}:difficulty==='hard'?{reaction:.26,spread:.016,aggression:1}:{reaction:.55,spread:.031,aggression:.87};
 if(t.think<=0){t.think=.3+rand()*.15;const enemies=tanks.filter(e=>e.alive&&e.team!==t.team&&p.distanceTo(e.group.position)<t.spec.view*(1-e.spec.camo*.25)&&los(t,e));enemies.sort((a,b)=>p.distanceToSquared(a.group.position)-p.distanceToSquared(b.group.position));const target=enemies[0]||null;if(target!==t.target)t.aimTime=0;t.target=target;}
 let goal={x:(t.team===0?-1:1)*4,z:0},retreat=t.hp<t.spec.hp*.24;
 if(t.target){const e=t.target.group.position,dist=p.distanceTo(e);goal=retreat?{x:p.x+(p.x-e.x)*.6,z:p.z+(p.z-e.z)*.6}:dist>34?{x:e.x,z:e.z}:{x:p.x,z:p.z};t.turretYaw=approach(t.turretYaw,Math.atan2(e.x-p.x,e.z-p.z),t.spec.turret*dt);t.aimTime+=dt;if(t.aimTime>cfg.reaction&&Math.abs(angle(Math.atan2(e.x-p.x,e.z-p.z)-t.turretYaw))<.12&&t.reload<=0){const target=e.clone().add(new V((rand()-.5)*dist*cfg.spread,1.45+(rand()-.5)*.8,(rand()-.5)*dist*cfg.spread));fire(t,target);t.aimTime=0;}}
 else{t.turretYaw=approach(t.turretYaw,t.yaw,t.spec.turret*dt);t.aimTime=0;}
 if(Math.hypot(goal.x-p.x,goal.z-p.z)>5){if(t.navTime<=0){t.path=route(p.x,p.z,goal.x,goal.z);t.navTime=1.6+rand();}while(t.path.length&&Math.hypot(t.path[0].x-p.x,t.path[0].z-p.z)<3.7)t.path.shift();const next=t.path[0]||goal;const desired=Math.atan2(next.x-p.x,next.z-p.z);const turn=angle(desired-t.yaw);t.yaw=approach(t.yaw,desired,t.spec.turn*dt);accelerateTank(t,t.stuck>1.5?-.6:cfg.aggression*Math.max(.12,1-Math.abs(turn)/1.8),dt,turn);if(!moveTank(t,dt)){t.stuck+=dt;t.yaw+=dt*(t.team===0?1:-1);if(t.stuck>1.5){t.path=[];t.navTime=0;if(t.stuck>3)t.stuck=0;}}else t.stuck=0;}else{accelerateTank(t,0,dt);moveTank(t,dt);}
 t.group.rotation.y=t.yaw;t.turret.rotation.y=angle(t.turretYaw-t.yaw);if(t.target){const e=t.target.group.position;const delta=e.clone().add(new V(0,1.4,0)).sub(p.clone().add(new V(0,2.05,0)));t.gunPivot.rotation.x=-Math.atan2(delta.y,Math.hypot(delta.x,delta.z));}
}
function vehicleEffects(t,dt,moved){t.effectClock-=dt;t.markClock-=dt;const p=t.group.position;if(t.effectClock<=0){t.effectClock=moved?.09:.28;const rear=new V(-Math.sin(t.yaw)*t.length*.44,1.35,-Math.cos(t.yaw)*t.length*.44).add(p);smoke(rear,moved?(arena===D.maps.winter?0xd7e0df:0x9d927b):0x5d6460,moved?.18:.11,moved?1.1:.55);if(moved){for(const side of [-1,1]){const dust=p.clone().add(new V(Math.cos(t.yaw)*side*t.width*.55,.12,-Math.sin(t.yaw)*side*t.width*.55));smoke(dust,arena===D.maps.winter?0xe1e7e5:arena===D.maps.desert?0xc5a879:0x817963,.24,1.8);}}}if(moved&&Math.abs(t.speed)>1&&t.markClock<=0){t.markClock=.16;for(const side of [-1,1]){const mark=new THREE.Mesh(trackGeo,trackMat);mark.rotation.x=-Math.PI/2;mark.rotation.z=-t.yaw;mark.position.set(p.x+Math.cos(t.yaw)*side*t.width*.5,height(p.x,p.z)+.035,p.z-Math.sin(t.yaw)*side*t.width*.5);mark.renderOrder=-1;world.add(mark);trackMarks.push({mesh:mark,life:32});}while(trackMarks.length>260){world.remove(trackMarks.shift().mesh);}}}
function groundSurface(){return arena===D.maps.winter?D.surfaces.snow:arena===D.maps.desert?D.surfaces.sand:D.surfaces.earth;}
function accelerateTank(t,throttle,dt,turn=0){
 if(t.suspension?.grounded===false)return;
 const p=t.group.position,dx=Math.sin(t.yaw)*2,dz=Math.cos(t.yaw)*2,slope=(height(p.x+dx,p.z+dz)-height(p.x-dx,p.z-dz))/4;
 t.speed=D.driveSpeed(t.spec,t.speed,throttle,slope,dt,turn,t.trackTime>0,groundSurface());
}
function moveTank(t,dt){
 const p=t.group.position,airborne=t.suspension?.grounded===false;
 if(airborne)t.yaw=t.suspension.yaw; // Tracks cannot steer a tank without ground contact.
 const sn=Math.sin(t.yaw),cs=Math.cos(t.yaw),surface=groundSurface();
 if(!airborne){
  const slope=(height(p.x+cs*2,p.z-sn*2)-height(p.x-cs*2,p.z+sn*2))/4;
  t.slip=D.frictionSpeed(t.slip||0,slope,dt,Math.abs(t.slip||0)<.001?surface.static:surface.kinetic);
  const total=Math.hypot(t.speed,t.slip);if(total>t.spec.speed){t.speed*=t.spec.speed/total;t.slip*=t.spec.speed/total;}
  t.velocityX=sn*t.speed+cs*t.slip;t.velocityZ=cs*t.speed-sn*t.slip;
 }
 const dx=(t.velocityX||0)*dt,dz=(t.velocityZ||0)*dt,r=t.width*.65,oldX=p.x,oldZ=p.z;
 const blockedByTank=(x,z)=>tanks.some(o=>o!==t&&(o.alive||o.wreck)&&Math.abs(p.y-o.group.position.y)<3&&Remaster.overlaps(t,x,z,o));
 if(!blocked(p.x+dx,p.z,r)&&!blockedByTank(p.x+dx,p.z))p.x+=dx;else t.velocityX=0;
 if(!blocked(p.x,p.z+dz,r)&&!blockedByTank(p.x,p.z+dz))p.z+=dz;else t.velocityZ=0;
 const travelled=Math.hypot(p.x-oldX,p.z-oldZ),didMove=travelled>.00001;
 t.speed=(t.velocityX||0)*sn+(t.velocityZ||0)*cs;t.slip=(t.velocityX||0)*cs-(t.velocityZ||0)*sn;
 Remaster.suspension(t,height,dt,airborne?0:(p.x-oldX)*sn+(p.z-oldZ)*cs);
 if(t.suspension.impact>2){if(t.isPlayer)shake=Math.min(.45,t.suspension.impact*.025);smoke(p.clone().add(new V(0,.2,0)),0x938577,.5,2);}
 if(t.alive&&t.suspension.grounded)vehicleEffects(t,dt,didMove);
 return didMove;
}
function muzzlePos(t){t.group.updateMatrixWorld(true);return t.gunPivot.localToWorld(new V(0,0,t.barrelLength+.5));}
function aimPoint(){ray.setFromCamera(new THREE.Vector2(0,0),camera);ray.far=800;const targets=[ground,...solidMeshes,...tanks.filter(t=>t!==player&&(t.alive||t.wreck)).flatMap(t=>[...t.hitMeshes,...(t.wreckCollider?[t.wreckCollider]:[])] )];const hit=ray.intersectObjects(targets,false)[0];aimHit=hit||null;return hit?hit.point:ray.ray.at(750,new V());}
function fire(t,target){if(countdown>0||t.reload>0||!t.alive)return;t.reload=t.spec.reload;const origin=muzzlePos(t),direction=target.clone().sub(origin).normalize();const actualYaw=Math.atan2(direction.x,direction.z);if(t.isPlayer&&Math.abs(angle(actualYaw-t.turretYaw))>.09){direction.x=Math.sin(t.turretYaw);direction.z=Math.cos(t.turretYaw);direction.normalize();}const precise=t.isPlayer?aiming:(t.remoteAim||false);const spread=t.spec.spread*(t.isPlayer?(precise?.28:.6):.4)*(1+Math.abs(t.speed)/t.spec.speed);direction.x+=(Math.random()-.5)*spread;direction.y+=(Math.random()-.5)*spread*.4;direction.z+=(Math.random()-.5)*spread;direction.normalize();const bullet=mesh(new THREE.CapsuleGeometry(.075,.55,2,5),new THREE.MeshBasicMaterial({color:0xfff0ad}),world);bullet.position.copy(origin);bullet.quaternion.setFromUnitVectors(up,direction);bullets.push({mesh:bullet,position:origin.clone(),velocity:direction.multiplyScalar(145),owner:t,life:2.7});burst(origin,0xffce79,15,.2);smoke(origin,0x77746d,.35,1.8);const flash=new THREE.PointLight(0xffb45c,28,22,2);flash.position.copy(origin);world.add(flash);particles.push({mesh:flash,velocity:new V(),life:.09,max:.09,size:1,gravity:0});sound('shot',t.isPlayer?1:.25);if(t.isPlayer)shake=.16;}
function burst(position,color,count=16,size=.5){for(let i=0;i<count;i++){const o=mesh(sphereGeo,mat(color),world);o.position.copy(position);const life=.35+Math.random()*.55;o.scale.setScalar(size*(.5+Math.random()));particles.push({mesh:o,velocity:new V((Math.random()-.5)*9,Math.random()*7,(Math.random()-.5)*9),life,max:life,size:o.scale.x});}}
function smoke(position,color,size=.3,speed=1){const material=new THREE.MeshBasicMaterial({color,transparent:true,opacity:.34,depthWrite:false});const o=mesh(sphereGeo,material,world);o.position.copy(position);o.scale.set(size,size*.65,size);const life=.8+Math.random()*.9;particles.push({mesh:o,velocity:new V((Math.random()-.5)*speed,.45+Math.random()*speed*.7,(Math.random()-.5)*speed),life,max:life,size,gravity:-.12,grow:1.8,fade:true});}
function addImpactHole(t,point,normal,amount){if(!normal)return;const material=new THREE.MeshBasicMaterial({color:amount>180?0x080807:0x171817,transparent:true,opacity:.92,depthWrite:false,polygonOffset:true,polygonOffsetFactor:-4});const hole=new THREE.Mesh(holeGeo,material),local=t.group.worldToLocal(point.clone()),q=t.group.getWorldQuaternion(new THREE.Quaternion()).invert(),n=normal.clone().applyQuaternion(q).normalize();hole.position.copy(local).addScaledVector(n,.025);hole.scale.setScalar(amount>180?.19:.11);hole.lookAt(local.clone().add(n));t.group.add(hole);t.holes.push(hole);while(t.holes.length>28){const old=t.holes.shift();t.group.remove(old);old.material.dispose();}}
function makeWreck(t){if(t.wreck)return;t.wreck=true;t.alive=false;t.speed=0;t.group.visible=true;const wreckMaterial=mat(0x353b38,.32,.96);wreckMaterial.transparent=false;wreckMaterial.opacity=1;wreckMaterial.depthWrite=true;wreckMaterial.depthTest=true;t.group.traverse(o=>{if(!o.isMesh||o.userData.collisionOnly||t.holes.includes(o))return;o.visible=true;o.material=Array.isArray(o.material)?o.material.map(()=>wreckMaterial):wreckMaterial;});}
function damageTank(t,amount,owner,point,normal){if(!t.alive||t.team===owner.team)return;let damage=Math.round(amount*(1-t.spec.armor/100)*(.91+Math.random()*.18));const crit=Math.random()<.08; if(crit){damage=Math.round(damage*1.25);t.trackTime=2;}damage=Math.min(t.hp,damage);t.hp-=damage;if(t.isPlayer&&damage>0){capture=0;hitText('ЗАХВАТ СБРОШЕН');}addImpactHole(t,point,normal,amount);if(owner.isPlayer){record.damage+=damage;hitText((crit?'КРИТИЧЕСКОЕ ПОПАДАНИЕ  ':'ПОПАДАНИЕ  ')+damage);sound('hit');}if(t.isPlayer){shake=.22;$('damageFlash').style.opacity=1;setTimeout(()=>$('damageFlash').style.opacity=0,160);}burst(point,0xffd487,18,.23);smoke(point,0x403d38,.32,1.2);if(t.hp<=0){makeWreck(t);burst(t.group.position.clone().add(new V(0,1,0)),0xdb8942,36,1.1);for(let i=0;i<8;i++)smoke(t.group.position.clone().add(new V((Math.random()-.5)*2,1+Math.random(),(Math.random()-.5)*2)),0x343532,.7,1.7);sound('boom',t.isPlayer?1:.55);if(owner.isPlayer){record.kills++;hitText('ПРОТИВНИК УНИЧТОЖЕН');}const line=document.createElement('div');line.textContent=`${owner.name} › ${t.name} · ${t.spec.name}`;line.style.color=owner.team===0?'#99d2c6':'#e99880';$('killfeed').prepend(line);while($('killfeed').children.length>5)$('killfeed').lastChild.remove();if(t.isPlayer){record.life=elapsed;$('tutorialHint').textContent='Танк уничтожен. Бой продолжается.';document.exitPointerLock?.();mouseDown=false;}}}
function hitText(text){$('hitMessage').textContent=text;clearTimeout(hitTimer);hitTimer=setTimeout(()=>$('hitMessage').textContent='',1300);}
function updateProjectiles(dt){world.updateMatrixWorld(true);for(let i=bullets.length-1;i>=0;i--){const b=bullets[i];b.velocity.y-=D.gravity*dt*.5;const distance=b.velocity.length()*dt;ray.set(b.position,b.velocity.clone().normalize());ray.far=distance;const targets=tanks.filter(t=>t!==b.owner&&(t.alive||t.wreck)).flatMap(t=>[...t.hitMeshes,...(t.wreckCollider?[t.wreckCollider]:[])]);const hits=ray.intersectObjects([ground,...solidMeshes,...targets],false);const hit=hits[0];b.life-=dt;if(hit){const t=hit.object.userData.tank,normal=hit.face?.normal.clone().transformDirection(hit.object.matrixWorld);if(t){if(t.wreck){burst(hit.point,0xffe1a0,14,.1);}else{const zone=Remaster.zone(hit,t),incidence=normal?Math.abs(normal.dot(b.velocity.clone().normalize())):1,result=D.penetration(b.owner.spec,t.spec,zone,incidence,b.owner.group.position.distanceTo(hit.point));if(Math.random()<result.chance)damageTank(t,b.owner.spec.damage,b.owner,hit.point,normal);else{burst(hit.point,0xffe1a0,14,.1);addImpactHole(t,hit.point,normal,50);if(b.owner.isPlayer)hitText(result.chance<.15?'РИКОШЕТ / НЕ ПРОБИТО':'НЕ ПРОБИТО');}}}else{burst(hit.point,0xffdf9a,13,.2);smoke(hit.point,0x6d675b,.25,1.1);}}if(hit||b.life<=0){world.remove(b.mesh);b.mesh.geometry.dispose();b.mesh.material.dispose();bullets.splice(i,1);}else{b.position.addScaledVector(b.velocity,dt);b.velocity.y-=D.gravity*dt*.5;b.mesh.position.copy(b.position);b.mesh.quaternion.setFromUnitVectors(up,b.velocity.clone().normalize());}}for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.life-=dt;if(p.life<=0){world.remove(p.mesh);if(p.fade)p.mesh.material?.dispose?.();particles.splice(i,1);}else{p.velocity.y-=(p.gravity??D.gravity)*dt;p.mesh.position.addScaledVector(p.velocity,dt);if(!p.fade&&p.mesh.isMesh){const floor=height(p.mesh.position.x,p.mesh.position.z)+p.size*.25;if(p.mesh.position.y<floor){p.mesh.position.y=floor;p.velocity.y=Math.max(0,-p.velocity.y*.22);const drag=Math.exp(-groundSurface().kinetic*D.gravity*dt);p.velocity.x*=drag;p.velocity.z*=drag;}}const ratio=p.life/p.max,scale=p.grow?p.size*(1+(1-ratio)*p.grow):p.size*ratio;p.mesh.scale.setScalar(scale);if(p.fade&&p.mesh.material)p.mesh.material.opacity=.34*ratio;}}for(let i=trackMarks.length-1;i>=0;i--){const m=trackMarks[i];m.life-=dt;if(m.life<5)m.mesh.material=trackMat;if(m.life<=0){world.remove(m.mesh);trackMarks.splice(i,1);}}}
function updateCamera(dt){const focus=player.alive?player:tanks.find(t=>t.alive&&t.team===player.team)||player;const p=focus.group.position;if(!player.alive)viewYaw+=dt*.045;const d=aiming?2.8:12,targetDistance=aiming?90:23;const target=p.clone().add(new V(Math.sin(viewYaw)*targetDistance,2.2+viewPitch*targetDistance,Math.cos(viewYaw)*targetDistance));const desired=p.clone().add(new V(-Math.sin(viewYaw)*d,aiming?3.15:6.4,-Math.cos(viewYaw)*d));const pivot=p.clone().add(new V(0,2.6,0));ray.set(pivot,desired.clone().sub(pivot).normalize());ray.far=desired.distanceTo(pivot);const obstruction=ray.intersectObjects(solidMeshes,false)[0];if(obstruction)desired.copy(ray.ray.at(Math.max(1,obstruction.distance-.6),new V()));desired.y=Math.max(desired.y,height(desired.x,desired.z)+1.5);camera.position.lerp(desired,1-Math.exp(-dt*10));if(shake>0){camera.position.x+=(Math.random()-.5)*shake;camera.position.y+=(Math.random()-.5)*shake;shake*=Math.exp(-dt*11);}const zoom=player?.spec.zoom||2.5,cameraFov=aiming?Math.max(12,60/zoom):60;camera.fov=THREE.MathUtils.lerp(camera.fov,cameraFov,1-Math.exp(-dt*(aiming?7:10)));camera.updateProjectionMatrix();camera.lookAt(target);}
function updateBattle(dt,frameTime){
 if(countdown>0){const delta=countdownClock===null?0:Math.max(0,(frameTime-countdownClock)/1000);countdownClock=frameTime;countdown=Math.max(0,countdown-delta);$('countNumber').textContent=Math.ceil(countdown);$('countdown').hidden=countdown<=0;updateCamera(dt);if(countdown===0){mouseDown=false;Object.keys(keys).forEach(k=>keys[k]=false);}return;}
 aiming=!!(keys.ShiftLeft||keys.ShiftRight);$('hud').classList?.toggle('aiming',aiming);elapsed+=dt;battleTime=Math.max(0,battleTime-dt);if(player.alive)record.life=elapsed;
 for(const t of tanks){if(!t.alive){accelerateTank(t,0,dt);moveTank(t,dt);continue;}t.reload=Math.max(0,t.reload-dt);t.trackTime=Math.max(0,t.trackTime-dt);if(t.isPlayer){const accel=(keys.KeyW||keys.ArrowUp?1:0)-(keys.KeyS||keys.ArrowDown?1:0);const turn=(keys.KeyA||keys.ArrowLeft?1:0)-(keys.KeyD||keys.ArrowRight?1:0);t.yaw+=turn*t.spec.turn*dt*(t.trackTime?.45:1);accelerateTank(t,accel,dt,turn);moveTank(t,dt);t.group.rotation.y=t.yaw;t.turretYaw=approach(t.turretYaw,viewYaw,t.spec.turret*dt);t.turret.rotation.y=angle(t.turretYaw-t.yaw);lastAimPoint.copy(aimPoint());const muzzle=muzzlePos(t);const delta=lastAimPoint.clone().sub(muzzle);t.gunPivot.rotation.x=THREE.MathUtils.clamp(-Math.atan2(delta.y,Math.hypot(delta.x,delta.z)),-.32,.22);if((mouseDown||keys.Space)&&!(matchMode==='lan'&&net?.role==='guest'))fire(t,lastAimPoint);}else if(!t.remote)updateBot(t,dt);}
 networkStep(dt);updateProjectiles(dt);updateCamera(dt);
 const onBase=tanks.filter(t=>t.alive&&t.suspension?.grounded!==false&&Math.hypot(t.group.position.x,t.group.position.z)<12),a=onBase.filter(t=>t.team===0).length,b=onBase.filter(t=>t.team===1).length;if(a&&!b){capture=Math.min(100,capture+dt*3*a);if(onBase.includes(player))record.capture+=dt;}else if(b&&!a)capture=Math.max(-100,capture-dt*3*b);else if(!a&&!b)capture*=Math.exp(-dt*.015);
 const allies=tanks.filter(t=>t.alive&&t.team===0),enemies=tanks.filter(t=>t.alive&&t.team===1);if(!(matchMode==='lan'&&net?.role==='guest')){if(!enemies.length||capture>=100){endBattle(true,capture>=100?'База под контролем вашей команды':'Все противники уничтожены');return;}if(!allies.length||capture<=-100){endBattle(false,capture<=-100?'Противник захватил базу':'Ваша команда уничтожена');return;}if(battleTime<=0){const aHP=allies.reduce((s,t)=>s+t.hp/t.spec.hp,0),bHP=enemies.reduce((s,t)=>s+t.hp/t.spec.hp,0);endBattle(aHP>bHP,'Время вышло. Итог по оставшейся прочности команд.');return;}}
 uiTick+=dt;if(uiTick>.1){uiTick=0;updateHUD();if(matchMode==='lan'&&player.team===1){$('alliesScore').textContent=tanks.filter(t=>t.alive&&t.team===1).length;$('enemiesScore').textContent=tanks.filter(t=>t.alive&&t.team===0).length;}}updateMarkers();if(engineGain){engineGain.gain.value=player.alive?.025+Math.abs(player.speed)*.0018:0;engineAudio.frequency.value=35+Math.abs(player.speed)*3;}
}
function updateMarkers(){for(const [t,el]of markers){if(!t.alive){el.hidden=true;continue;}const friendly=t.team===player.team;el.className='marker '+(friendly?'friendly':'');const dist=player.group.position.distanceTo(t.group.position),visible=friendly||(dist<player.spec.view*(1-t.spec.camo*.25)&&los(player,t));if(visible&&!friendly&&!t.seen&&player.alive){t.seen=true;record.spotted++;}t.visible=visible;const point=t.group.position.clone().add(new V(0,4.1,0)).project(camera);el.hidden=!visible||point.z>1||point.z<0||Math.abs(point.x)>1.15||Math.abs(point.y)>1.15;if(!el.hidden){el.style.left=(point.x*.5+.5)*innerWidth+'px';el.style.top=(-point.y*.5+.5)*innerHeight+'px';el.innerHTML=`${friendly?'◆':'◇'} ${t.spec.name}<div><i style="width:${t.hp/t.spec.hp*100}%"></i></div>${Math.ceil(t.hp)} · ${Math.round(dist)} м`;}}}
function updatePenetration(){const dot=$('penetrationDot'),label=$('penetrationLabel'),t=aimHit?.object.userData.tank;if(!t||!t.alive||t.team===player.team){dot.style.background='#dbe2dc';label.textContent=aiming?player.spec.zoom.toFixed(1)+'×':'';return;}const normal=aimHit.face?.normal.clone().transformDirection(aimHit.object.matrixWorld),direction=aimHit.point.clone().sub(muzzlePos(player)).normalize(),result=D.penetration(player.spec,t.spec,Remaster.zone(aimHit,t),normal?Math.abs(normal.dot(direction)):1,player.group.position.distanceTo(aimHit.point));dot.style.background=result.color;dot.style.boxShadow='0 0 12px '+result.color;label.style.color=result.color;label.textContent=(result.chance>=.75?'ПРОБИТИЕ':result.chance>=.25?'РИСК НЕПРОБИТИЯ':'БРОНЯ НЕ ПРОБИВАЕТСЯ')+' · '+Math.round(result.chance*100)+'%';}
function updateHUD(){updatePenetration();const a=tanks.filter(t=>t.alive&&t.team===0).length,b=tanks.filter(t=>t.alive&&t.team===1).length;$('alliesScore').textContent=a;$('enemiesScore').textContent=b;$('timer').textContent=`${Math.floor(battleTime/60).toString().padStart(2,'0')}:${Math.floor(battleTime%60).toString().padStart(2,'0')}`;$('hpText').textContent=`${Math.ceil(player.hp)} / ${player.spec.hp}`;$('hpBar').style.width=player.hp/player.spec.hp*100+'%';$('speedText').textContent=Math.round(Math.abs(player.speed)*3.6)+' км/ч';$('reloadLabel').textContent=!player.alive?'МАШИНА УНИЧТОЖЕНА':player.reload>.05?`ПЕРЕЗАРЯДКА ${player.reload.toFixed(1)} с`:'ОРУДИЕ ГОТОВО';$('reloadBar').style.width=(1-player.reload/player.spec.reload)*100+'%';$('objectiveText').textContent=Math.abs(capture)>1?`${capture>0?'ВАША КОМАНДА':'ПРОТИВНИК'} · БАЗА A ${Math.floor(Math.abs(capture))}%`:'ЗАХВАТИТЕ БАЗУ A';$('captureBar').style.width=Math.abs(capture)+'%';$('captureBar').style.background=capture>=0?'#80c7c0':'#e78c72';$('range').textContent=player.reload>.05?`${player.reload.toFixed(1)} С`:`${Math.round(player.group.position.distanceTo(lastAimPoint))} М · ББ`;document.querySelector('.reticle').style.transform=`scale(${(aiming?.66:1)+Math.abs(player.speed)*.015+player.reload*.07})`;drawMinimap();if(elapsed>22&&!save.tutorial){save.tutorial=true;persist();$('tutorialHint').textContent='';}}
function drawMinimap(){const ctx=$('minimap').getContext('2d'),size=220,scale=size/arena.size;ctx.fillStyle=arena===D.maps.desert?'#655d47':arena===D.maps.winter?'#56686e':'#394d43';ctx.fillRect(0,0,size,size);ctx.strokeStyle='#ffffff0e';ctx.lineWidth=1;for(let i=0;i<=5;i++){ctx.beginPath();ctx.moveTo(i*44,0);ctx.lineTo(i*44,220);ctx.moveTo(0,i*44);ctx.lineTo(220,i*44);ctx.stroke();}const X=x=>110+x*scale,Z=z=>110-z*scale;ctx.fillStyle='#adbaab50';for(const o of obstacles){ctx.beginPath();ctx.arc(X(o.x),Z(o.z),o.r*scale,0,Math.PI*2);ctx.fill();}ctx.strokeStyle='#ddc88b';ctx.beginPath();ctx.arc(110,110,12*scale,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#eddbab';ctx.font='11px sans-serif';ctx.fillText('A',107,114);for(const t of tanks){if(!t.alive||(t.team===1&&!t.visible))continue;ctx.save();ctx.translate(X(t.group.position.x),Z(t.group.position.z));ctx.rotate(t.yaw);ctx.fillStyle=t.isPlayer?'#fff0ba':t.team===0?'#83d0c1':'#ef997a';ctx.beginPath();ctx.moveTo(0,-5);ctx.lineTo(4,4);ctx.lineTo(-4,4);ctx.closePath();ctx.fill();if(t.isPlayer){ctx.strokeStyle='#fff0ba70';ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(-11,-24);ctx.moveTo(0,0);ctx.lineTo(11,-24);ctx.stroke();}ctx.restore();}}
function endBattle(win,reason){if(state!=='battle')return;if(matchMode==='lan'&&net?.role==='host')netSend('end',{winner:win?player.team:1-player.team,reason});updateHUD();state='result';paused=false;Platform.gameplay(false);document.exitPointerLock?.();mouseDown=false;record.win=win;record.survived=player.alive;const reward=D.reward(record);save.silver+=reward.silver;save.xp+=reward.xp;save.battles++;if(win)save.wins++;persist();if(engineGain)engineGain.gain.value=0;$('scoreboard').hidden=true;showModal(`<div class="end-medal">${win?'◈':'◇'}</div><div class="result-title"><small>ОПЕРАЦИЯ ЗАВЕРШЕНА</small><h2>${win?'Победа':'Поражение'}</h2><p>${reason}</p></div><div class="row"><span>Нанесённый урон</span><b>${record.damage}</b></div><div class="row"><span>Уничтожено / обнаружено</span><b>${record.kills} / ${record.spotted}</b></div><div class="row"><span>Время жизни / захват базы</span><b>${Math.floor(record.life)} с / ${Math.floor(record.capture)} с</b></div><div class="reward"><div>+${reward.silver} ◉<small>СЕРЕБРО</small></div><div>+${reward.xp} ✦<small>ОПЫТ</small></div></div><p class="help-note">Участие ${reward.parts.participation} · урон ${reward.parts.damage} · фраги ${reward.parts.kills} · победа ${reward.parts.victory} · разведка ${reward.parts.spotting} · база ${reward.parts.objective} · выживание ${reward.parts.survival}</p><button id="returnGarage" class="primary">В АНГАР →</button>`);$('returnGarage').onclick=()=>{net=null;matchMode='solo';hangar();};}
function showModal(html){$('modalContent').innerHTML=html;$('modal').hidden=false;}
function pause(){if(state!=='battle'||paused)return;if(matchMode==='lan'){toast('Сетевой бой нельзя поставить на паузу');return;}paused=true;countdownClock=null;mouseDown=false;aiming=false;Object.keys(keys).forEach(k=>keys[k]=false);Platform.gameplay(false);document.exitPointerLock?.();if(engineGain)engineGain.gain.value=0;showModal('<div class="eyebrow">БОЙ ПРИОСТАНОВЛЕН</div><h2>Пауза</h2><p>Ваш танк и команды ждут возвращения.</p><button id="resume" class="primary">ПРОДОЛЖИТЬ →</button><button id="pauseSettings" class="secondary">Настройки</button><button id="leave" class="text-btn">Завершить бой и получить награду</button>');$('resume').onclick=resume;$('pauseSettings').onclick=settings;$('leave').onclick=()=>endBattle(false,'Досрочный выход из боя. Награда за участие начислена.');}
function resume(){paused=false;$('modal').hidden=true;initAudio();Platform.gameplay(true);}
function settings(){const inBattle=state==='battle';showModal(`<div class="eyebrow">ПАРАМЕТРЫ</div><h2>Настройки</h2><label for="volume">Громкость</label><input id="volume" type="range" min="0" max="1" step=".05" value="${save.settings.volume}"><label for="quality">Графика</label><select id="quality"><option value="high">Максимальная — PBR, AO, тени 4K</option><option value="low">Производительность — без постобработки</option></select><label for="difficulty">Боты — со следующего боя</label><select id="difficulty"><option value="easy">Лёгкие</option><option value="normal">Обычные</option><option value="hard">Сложные</option></select><label for="sensitivity">Чувствительность мыши</label><input id="sensitivity" type="range" min=".25" max="2.5" step=".05" value="${save.settings.sensitivity}"><button id="saveSettings" class="primary">СОХРАНИТЬ</button><button id="closeSettings" class="text-btn">← Назад</button>`);$('quality').value=save.settings.quality;$('difficulty').value=save.settings.difficulty;$('volume').oninput=()=>{initAudio();if(master)master.gain.value=+$('volume').value;};const back=()=>{if(master)master.gain.value=save.settings.volume;if(inBattle){paused=false;pause();}else $('modal').hidden=true;};$('closeSettings').onclick=back;$('saveSettings').onclick=()=>{save.settings={volume:+$('volume').value,quality:$('quality').value,difficulty:$('difficulty').value,sensitivity:+$('sensitivity').value};persist();applyQuality();back();};}
function applyQuality(){renderer.shadowMap.enabled=save.settings.quality==='high';renderer.setPixelRatio(Math.min(devicePixelRatio,save.settings.quality==='high'?2:1));if(scene)scene.traverse(o=>{if(o.material)o.material.needsUpdate=true;});}
function details(){const s=D.stats(chosen(),save.levels[save.selected]);showModal(`<div class="eyebrow">ПАСПОРТ МАШИНЫ · ${s.nation.toUpperCase()}</div><h2>${s.name}</h2><table>${[['Класс',s.cls],['Уровень',s.level+'/5'],['Прочность',s.hp+' HP'],['Урон',s.damage],['Перезарядка',s.reload+' с'],['Скорость',Math.round(s.speed*3.6)+' км/ч'],['Поворот корпуса',(s.turn*180/Math.PI).toFixed(0)+' °/с'],['Поворот башни',(s.turret*180/Math.PI).toFixed(0)+' °/с'],['Снижение урона бронёй',s.armor+'%'],['Дальность обзора',s.view+' м'],['Оптическое увеличение',s.zoom.toFixed(2)+'×'],['Точность',Math.round((1-s.spread)*1000)/10+'%'],['Разброс',s.spread.toFixed(3)+' рад'],['Время сведения',s.aim.toFixed(2)+' с'],['Прочность ходовой',s.tracks+' (паспорт)'],['Маскировка',Math.round(s.camo*100)+'%']].map(([k,v])=>`<tr><td>${k}</td><td>${v}</td></tr>`).join('')}</table><p class="help-note">Оптика включается удержанием Shift. Увеличение зависит от класса, нации и уровня модернизации.</p><button id="closeDetails" class="secondary">← Назад в ангар</button>`);$('closeDetails').onclick=()=>$('modal').hidden=true;}
function help(){showModal('<div class="eyebrow">КУРС МОЛОДОГО КОМАНДИРА</div><h2>Займите свой рубеж</h2><p>В одиночном режиме вы и два союзных бота сражаетесь против трёх противников. В локальной сети — честный бой 1 × 1.</p><div class="tutorial-keys"><span><kbd>W / S</kbd> вперёд / назад</span><span><kbd>A / D</kbd> поворот корпуса</span><span><kbd>Мышь</kbd> башня и камера</span><span><kbd>ЛКМ</kbd> выстрел</span><span><kbd>Shift</kbd> оптика танка</span><span><kbd>Пробел</kbd> выстрел</span><span><kbd>Tab</kbd> состав команд</span><span><kbd>Esc</kbd> пауза</span></div><p>Удерживайте Shift для оптического прицела. Его увеличение зависит от характеристик выбранной машины и растёт с модернизацией.</p><p>Для боя через Radmin хост запускает PLAY.cmd, создаёт лобби и передаёт другу адрес сервера и пятизначный код.</p><button id="closeHelp" class="primary">ПОНЯТНО →</button>');$('closeHelp').onclick=()=>{$('modal').hidden=true;};}
function scoreboard(){if(state!=='battle'||paused)return;$('scoreboard').hidden=false;const order=player.team===0?[0,1]:[1,0];$('teamList').innerHTML=order.map((team,index)=>`<p class="${index===0?'ally':'enemy'}">${index===0?'ВАША КОМАНДА':'ПРОТИВНИК'}</p>`+tanks.filter(t=>t.team===team).map(t=>`<div class="team-row ${t.alive?'':'dead'}"><span>${t.name} · ${t.spec.name}</span><b>${t.alive?Math.ceil(t.hp)+' HP':'Уничтожен'}</b></div>`).join('')).join('');}
function bind(){
 $('armorBtn').onclick=()=>{armorView=!armorView;Remaster.armorMask(preview,armorView,D.stats(chosen(),save.levels[save.selected]));$('armorLegend').hidden=!armorView;renderGarage();};$('unlockBtn').onclick=()=>{if(D.unlock(save,save.selected)){persist();renderGarage();toast('Танк исследован и куплен');}};
 $('fullscreenBtn').onclick=()=>{if(document.fullscreenElement)document.exitFullscreen?.();else document.documentElement.requestFullscreen?.()?.catch?.(()=>toast('Откройте игру в отдельном окне браузера.'));};
 $('battleBtn').onclick=()=>{$('modeSelect').value==='lan'?showLan():startBattle();};$('upgradeBtn').onclick=()=>{if(D.upgrade(save,save.selected)){persist();renderGarage();sound('ui');toast('Модернизация завершена. Танк стал сильнее.');}};$('settingsBtn').onclick=settings;$('helpBtn').onclick=help;$('detailsBtn').onclick=details;$('pauseBtn').onclick=pause;$('mapSelect').onchange=()=>{save.map=$('mapSelect').value;persist();updateMapCard();};$('modeSelect').onchange=updateModeCard;
 window.addEventListener('keydown',e=>{if(['Space','Tab','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code)&&state==='battle')e.preventDefault();keys[e.code]=true;if(e.code==='Escape'){if(state==='battle'){if(paused)resume();else pause();}else if(state==='garage')$('modal').hidden=true;}if(e.code==='Tab')scoreboard();});window.addEventListener('keyup',e=>{keys[e.code]=false;if(e.code==='Tab')$('scoreboard').hidden=true;});
 const canvas=$('world');canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('mousedown',e=>{initAudio();if(state==='garage') {drag=true;dragX=e.clientX;return;}if(state!=='battle'||paused||!player.alive)return;if(e.button===0){mouseDown=true;if(!document.pointerLockElement)canvas.requestPointerLock?.()?.catch?.(()=>{});}});window.addEventListener('mouseup',()=>{mouseDown=false;drag=false;});
 window.addEventListener('mousemove',e=>{if(state==='garage'&&drag){preview.group.rotation.y+=(e.clientX-dragX)*.008;dragX=e.clientX;}if(state==='battle'&&!paused&&player.alive){if(document.pointerLockElement){viewYaw-=e.movementX*.0025*save.settings.sensitivity;viewPitch=THREE.MathUtils.clamp(viewPitch-e.movementY*.0015*save.settings.sensitivity,-.28,.65);}else{const nx=e.clientX/innerWidth-.5;keys.edgeTurn=Math.abs(nx)>.13?-nx*1.6:0;viewPitch=THREE.MathUtils.clamp((.5-e.clientY/innerHeight)*.6,-.28,.4);}}});
 document.addEventListener('pointerlockchange',()=>{if(!document.pointerLockElement&&state==='battle'&&!paused&&player?.alive)pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden){pause();audio?.suspend();}});window.addEventListener('blur',()=>{Object.keys(keys).forEach(k=>keys[k]=false);pause();audio?.suspend();});window.addEventListener('resize',()=>{renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();});
}
function animate(now){const dt=Math.min(.045,(now-lastTime)/1000||.016);lastTime=now;if(state==='garage'){if(preview&&!drag)preview.group.rotation.y+=dt*.07;}else if(state==='battle'&&!paused){if(!document.pointerLockElement)viewYaw+=(keys.edgeTurn||0)*dt;updateBattle(dt,now);}if(state==='battle'&&player){const sun=scene.userData.sun,p=player.group.position;sun.position.set(p.x-65,p.y+105,p.z+55);sun.target.position.copy(p);sun.target.updateMatrixWorld();}Remaster.render(renderer,scene,camera,save.settings.quality==='high');}
try{renderer=new THREE.WebGLRenderer({canvas:$('world'),antialias:true,powerPreference:'high-performance'});renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.04;camera=new THREE.PerspectiveCamera(45,innerWidth/innerHeight,.15,2400);applyQuality();bind();hangar();renderer.render(scene,camera);$('loading').hidden=true;Platform.markReady();renderer.setAnimationLoop(animate);Platform.init((cloud,started)=>{if(state==='garage'&&save.updated<started&&cloud.updated>save.updated){save=cloud;hangar();toast('Облачный прогресс восстановлен');}},pause);}
catch(error){console.error(error);$('loading').innerHTML='<h1>Не удалось запустить 3D</h1><p>Включите аппаратное ускорение в браузере и обновите драйвер видеокарты.</p><p>'+String(error.message).replace(/[<>]/g,'')+'</p>';}
// Read-only inspection, useful for support and acceptance tests.
window.gameStatus=()=>({state,paused,countdown,armorView,owned:{...save.owned},map:save.map,tank:save.selected,mode:matchMode,network:net?{role:net.role,code:net.code,players:net.players?.length||0}:null,silver:save.silver,levels:{...save.levels},elapsed,camera:{fov:camera?.fov,zoom:camera?.zoom,aiming},player:player?{team:player.team,hp:player.hp,x:player.group.position.x,z:player.group.position.z,reload:player.reload,zoom:player.spec.zoom}:null,teams:tanks.map(t=>({team:t.team,hp:t.hp,alive:t.alive,x:t.group.position.x,z:t.group.position.z})),drawCalls:renderer?.info.render.calls});
})();
